"""The labelled set the player-intent interpreter is measured against.

Built 2026-09-27, when the user asked for an interpreter "first — the whole app hinges on
consistently good narration and accuracy". Every line is something a player typed or
would type; every label is what they meant, written by hand. Sources:

  * script:<name>   tools/narrator_audit.py's scripted sessions (the live runs of 2026-09)
  * playtest        player lines quoted in docs/playtest-*.md
  * failure         a sentence a word-detector misread in a live run, and what it meant
  * authored        a construction the literature says breaks parsers: several actions in
                    one sentence, a relative clause that names somebody, a time or a
                    condition, speech, a question, a claim

The frame (gm/interpret.py holds the schema): an ordered list of actions, each an `act`
from a closed list and slots quoted from the sentence — `target` (a person or creature),
`object` (a thing), `place`, `time`, `says` (what is said or asked, reported or quoted).
`question` is a line asked of the game rather than done in it. `claims` are outcomes or
facts the player asserts rather than attempts ("I am the lost heir").

Conventions, so labels are consistent:
  * a purpose clause is an action: "I head for the stables to ask about a horse" is go,
    then talk — and since 2026-10-03 the talk is `commit="intended"`: what the player
    means to do next is context the plan is shown, never an op of this turn.
  * commitment (`A(act, commit, …)`): done; tried ("I try to…", an attempt with a roll);
    intended (a purpose clause, "who will…", "I'm going to…", "I want to…"); asked ("would
    you buy it?"). "I'm going to the chapel" is going, done; "I'm going to light a candle"
    is intended.
  * looking for a PERSON is `seek` (target); for a thing or a place, `search` (object).
  * asking somebody something is `talk` with the question in `says`; `target` only when
    the sentence names who ("her", "the guard"), never guessed.
  * slots are verbatim spans, trimmed of the leading article only when the sentence has
    none; the scorer compares them without articles, determiners or case.
"""
from __future__ import annotations


def A(act: str, commit: str = "done", **slots) -> dict:
    """One action. `commit` is how far it is done (gm/interpret.py `COMMITS`): done,
    tried, intended or asked — labelled on every line since 2026-10-03 (round 2 of lane F);
    "done" unless the line says otherwise."""
    return {"act": act, "commit": commit, **{k: v for k, v in slots.items() if v is not None}}


def G(text: str, actions: list, source: str, *, question: bool = False,
      claims: tuple = (), dev: bool = False) -> dict:
    """`dev`: a line the reader's fixes may be written from (with the first 60). Every
    other line is held out: its misses are never printed (tools/interpreter_bench.py)."""
    return {"text": text, "actions": actions, "source": source, "question": question,
            "claims": list(claims), "dev": dev}


GOLD = [
    # --- script:town -------------------------------------------------------------------
    G("I look around and take stock of the street.", [A("look", place="the street")], "script:town"),
    G("I ask the nearest stallholder what work there is.",
      [A("talk", target="the nearest stallholder", says="what work there is")], "script:town"),
    G("I ask them who runs this quarter.", [A("talk", target="them", says="who runs this quarter")], "script:town"),
    G("I head for the smith to see what he has on the rack.",
      [A("seek", target="the smith"),
       A("look", "intended", object="what he has on the rack")], "script:town"),
    G("I ask the smith about the ore he uses.",
      [A("talk", target="the smith", says="about the ore he uses")], "script:town"),
    G("I leave the shop and walk out towards the gate.",
      [A("leave", place="the shop"), A("go", place="the gate")], "script:town"),
    G("I ask the gate guard what lies north.", [A("talk", target="the gate guard", says="what lies north")], "script:town"),
    G("I walk out into the grassland beyond the wall.", [A("go", place="the grassland beyond the wall")], "script:town"),
    G("I look for tracks in the grass.", [A("search", object="tracks in the grass")], "script:town"),
    G("I make camp and sleep until dawn.", [A("rest", time="until dawn")], "script:town"),
    # --- script:strangers ----------------------------------------------------------------
    G("I look along the street for someone who knows the roads north, and ask them.",
      [A("seek", target="someone who knows the roads north"), A("talk", target="them")], "script:strangers"),
    G("I find somebody selling bread and ask what a loaf costs.",
      [A("seek", target="somebody selling bread"), A("talk", says="what a loaf costs")], "script:strangers"),
    G("I ask around for a healer.", [A("seek", target="a healer")], "script:strangers"),
    G("I look for whoever keeps the inn and ask for a room.",
      [A("seek", target="whoever keeps the inn"), A("talk", says="for a room")], "script:strangers"),
    G("I wave down a passing carter and ask where he is headed.",
      [A("seek", target="a passing carter"), A("talk", says="where he is headed")], "script:strangers"),
    G("I look for a child who might run a message for a coin.",
      [A("seek", target="a child who might run a message for a coin")], "script:strangers"),
    G("I find someone who looks like they know the city's gossip and buy them a drink.",
      [A("seek", target="someone who looks like they know the city's gossip"),
       A("give", target="them", object="a drink")], "script:strangers"),
    G("I ask around for a guide who knows the grassland.",
      [A("seek", target="a guide who knows the grassland")], "script:strangers"),
    G("I look for a scribe who can read a letter for me.",
      [A("seek", target="a scribe who can read a letter for me")], "script:strangers"),
    G("I find the oldest person on the street and ask what this quarter was like once.",
      [A("seek", target="the oldest person on the street"),
       A("talk", says="what this quarter was like once")], "script:strangers"),
    # --- script:provoke --------------------------------------------------------------------
    G("I look around at the people standing nearest me.",
      [A("look", target="the people standing nearest me")], "script:provoke"),
    G("I tell the biggest man here that I have seen better fighters in a nursery.",
      [A("insult", target="the biggest man here", says="that I have seen better fighters in a nursery")],
      "script:provoke"),
    G("I laugh in his face and tell him to do something about it.",
      [A("insult", target="his"), A("talk", target="him", says="to do something about it")], "script:provoke"),
    G("I call him a coward in front of his friends.", [A("insult", target="him", says="a coward")], "script:provoke"),
    G("I tell his friends he cried when the last man stood up to him.",
      [A("insult", target="his friends", says="he cried when the last man stood up to him")], "script:provoke"),
    G("I lean in and tell him his wife is a better fighter than he is.",
      [A("insult", target="him", says="his wife is a better fighter than he is")], "script:provoke"),
    G("I turn my back on him and tell the barkeep he smells.",
      [A("insult", target="him"), A("insult", target="the barkeep", says="he smells")], "script:provoke"),
    G("I tell the whole room he is all talk.",
      [A("insult", target="the whole room", says="he is all talk")], "script:provoke"),
    G("I stay where I am and smile at him.", [A("wait"), A("other", target="him")], "script:provoke"),
    G("I tell him I am still waiting.", [A("talk", target="him", says="I am still waiting")], "script:provoke"),
    # --- script:discover ---------------------------------------------------------------------
    G("I ask where the dockhands drink, and go there.",
      [A("talk", says="where the dockhands drink"), A("go", place="there")], "script:discover"),
    G("I look for somewhere that sells rope and lamp oil.",
      [A("search", object="somewhere that sells rope and lamp oil")], "script:discover"),
    G("I find a quiet shrine and sit a while.",
      [A("search", object="a quiet shrine"), A("wait", time="a while")], "script:discover"),
    G("I head for the stables to ask about a horse.",
      [A("go", place="the stables"), A("talk", "intended", says="about a horse")],
      "script:discover"),
    G("I look for a pawnbroker who asks no questions.",
      [A("seek", target="a pawnbroker who asks no questions")], "script:discover"),
    G("I ask around for the best cook in town and go to where they work.",
      [A("seek", target="the best cook in town"), A("go", place="where they work")], "script:discover"),
    G("I go looking for the bathhouse.", [A("search", object="the bathhouse")], "script:discover"),
    G("I look for a bookseller.", [A("seek", target="a bookseller")], "script:discover"),
    G("I find a back alley where nobody will see me count my coin.",
      [A("search", object="a back alley where nobody will see me count my coin"),
       A("other", "intended", object="my coin")], "script:discover"),
    G("I head out of town to wherever the charcoal burners work.",
      [A("go", place="wherever the charcoal burners work")], "script:discover"),
    # --- script:return / calling / homes / buying ----------------------------------------------
    G("I find somebody selling bread in the market and ask what a loaf costs.",
      [A("seek", target="somebody selling bread in the market"), A("talk", says="what a loaf costs")],
      "script:return"),
    G("I ask her name.", [A("talk", target="her", says="her name")], "failure"),
    G("I walk over to the well.", [A("go", place="the well")], "script:return"),
    G("I sit by the well until well after dark.",
      [A("wait", place="the well", time="until well after dark")], "script:return"),
    G("I go back to the market.", [A("go", place="the market")], "script:return"),
    G("I ask around for the woman who sold me bread.",
      [A("seek", target="the woman who sold me bread")], "failure"),
    G("I find somewhere to sleep until morning.",
      [A("search", object="somewhere to sleep"), A("rest", "intended", time="until morning")],
      "failure"),
    G("I go to the market and look for the bread seller.",
      [A("go", place="the market"), A("seek", target="the bread seller")], "failure"),
    G("I take the road to the nearest town.", [A("journey", place="the nearest town")], "script:return"),
    G("I take the road back to the town I just left.",
      [A("journey", place="the town I just left")], "script:return"),
    G("I greet her by name.", [A("talk", target="her")], "script:return"),
    G("I buy a loaf from her and ask her name.",
      [A("buy", target="her", object="a loaf"), A("talk", says="her name")], "script:calling"),
    G("I wait at the well until ten at night.",
      [A("wait", place="the well", time="until ten at night")], "failure"),
    G("I ask around where the bread seller lives.",
      [A("seek", target="the bread seller", place="where the bread seller lives")], "script:calling"),
    G("I go to her house.", [A("call_on", target="her", place="her house")], "script:calling"),
    G("I thank her, say goodnight and leave.",
      [A("talk", target="her", says="goodnight"), A("leave")], "script:calling"),
    G("I go to the market.", [A("go", place="the market")], "script:calling"),
    G("I try to buy a coil of rope.", [A("buy", "tried", object="a coil of rope")], "failure"),
    G("I go to the market and buy a coil of rope.",
      [A("go", place="the market"), A("buy", object="a coil of rope")], "failure"),
    G("I wait at the well until two in the morning.",
      [A("wait", place="the well", time="until two in the morning")], "script:homes"),
    G("I pick the lock on her door.", [A("break_in", target="her", object="the lock on her door")], "script:homes"),
    G("I kick in her door.", [A("break_in", target="her", object="her door")], "script:homes"),
    G("I try to buy a loaf of bread.", [A("buy", object="a loaf of bread")], "script:buying"),
    G("I want to buy some torches.", [A("buy", object="some torches")], "script:buying"),
    G("I buy a dragon's egg.", [A("buy", object="a dragon's egg")], "script:buying"),
    # --- script:fight / kills ------------------------------------------------------------------
    G("I walk into the worst tavern on the street.",
      [A("go", place="the worst tavern on the street")], "script:fight"),
    G("I pick a fight with the biggest man in the room.",
      [A("insult", target="the biggest man in the room")], "script:fight"),
    G("I punch him in the face.", [A("attack", target="him")], "script:fight"),
    G("I punch him again.", [A("attack", target="him")], "script:fight"),
    G("I keep hitting him.", [A("attack", target="him")], "script:fight"),
    G("I grab him and throw him over a table.",
      [A("attack", target="him"), A("attack", target="him", place="over a table")], "script:fight"),
    G("I stand over him and tell him to stay down.",
      [A("talk", target="him", says="to stay down")], "script:fight"),
    G("I take what he was carrying.", [A("take", object="what he was carrying", target="he")], "script:fight"),
    G("I walk out before anyone else decides to try me.", [A("leave")], "script:fight"),
    G("I find somewhere quiet and sit down.",
      [A("search", object="somewhere quiet"), A("rest")], "script:fight"),
    G("I punch him in the face as hard as I can.", [A("attack", target="him")], "script:kills"),
    G("I hit him again and do not stop until he goes down.",
      [A("attack", target="him", time="until he goes down")], "script:kills"),
    G("I finish him.", [A("attack", target="him")], "script:kills"),
    G("I turn on the nearest of his friends and hit him.",
      [A("attack", target="the nearest of his friends")], "script:kills"),
    G("I hit him again, harder.", [A("attack", target="him")], "script:kills"),
    G("I put him down for good.", [A("attack", target="him")], "script:kills"),
    G("I look for anyone else who wants to try me.",
      [A("seek", target="anyone else who wants to try me")], "script:kills"),
    G("I go for the next one who steps up.", [A("attack", target="the next one who steps up")], "script:kills"),
    G("I keep hitting him until he stops moving.",
      [A("attack", target="him", time="until he stops moving")], "script:kills"),
    G("I stand over the bodies and look around the room.",
      [A("look", place="the room")], "script:kills"),
    # --- script:long -------------------------------------------------------------------------
    G("I ask what they are selling today.", [A("talk", says="what they are selling today")], "script:long"),
    G("I count what coin I have.", [A("other", object="what coin I have")], "script:long"),
    G("I ask who I should speak to about work outside the walls.",
      [A("talk", says="who I should speak to about work outside the walls")], "script:long"),
    G("I walk down towards the water.", [A("go", place="the water")], "script:long"),
    G("I watch the boats for a while.", [A("look", object="the boats", time="for a while")], "script:long"),
    G("I ask a boatman where the river goes.",
      [A("talk", target="a boatman", says="where the river goes")], "script:long"),
    G("I ask him what he carries downstream.", [A("talk", target="him", says="what he carries downstream")],
      "script:long"),
    G("I buy something to eat from a stall.",
      [A("buy", object="something to eat", place="a stall")], "script:long"),
    G("I eat it while I walk.", [A("consume", object="it")], "script:long"),
    G("I ask him what he would charge to mend a blade.",
      [A("talk", target="him", says="what he would charge to mend a blade")], "script:long"),
    G("I look at what else is on the rack.", [A("look", object="what else is on the rack")], "script:long"),
    G("I ask him whether the road is safe.", [A("talk", target="him", says="whether the road is safe")],
      "script:long"),
    G("I ask when the gate closes.", [A("talk", says="when the gate closes")], "script:long"),
    G("I follow the tracks a while.", [A("follow", object="the tracks", time="a while")], "script:long"),
    G("I stop and listen.", [A("look")], "script:long"),
    G("I climb the nearest rise to see further.",
      [A("athletics", place="the nearest rise"), A("look")], "script:long"),
    G("I look back the way I came.", [A("look", place="the way I came")], "script:long"),
    G("I keep walking north until the light starts to go.",
      [A("go", place="north", time="until the light starts to go")], "script:long"),
    G("I check my things before I set off.", [A("other", object="my things")], "script:long"),
    G("I look for water.", [A("search", object="water")], "script:long"),
    G("I drink and fill what I can carry.", [A("consume"), A("gather", object="what I can carry")],
      "script:long"),
    G("I forage for anything worth taking.", [A("gather", object="anything worth taking")], "script:long"),
    G("I look at what I have gathered.", [A("look", object="what I have gathered")], "script:long"),
    G("I walk on towards the treeline.", [A("go", place="the treeline")], "script:long"),
    G("I step in under the trees.", [A("go", place="under the trees")], "script:long"),
    G("I listen for anything moving.", [A("look", object="anything moving")], "script:long"),
    G("I look for a way through.", [A("search", object="a way through")], "script:long"),
    G("I follow the ground where it falls away.",
      [A("follow", object="the ground where it falls away")], "script:long"),
    G("I come out the other side and look around.",
      [A("go", place="the other side"), A("look")], "script:long"),
    G("I find the ruin the guard mentioned.", [A("search", object="the ruin the guard mentioned")],
      "script:long"),
    G("I walk the outside of it first.", [A("go", place="the outside of it")], "script:long"),
    G("I look for a way in.", [A("search", object="a way in")], "script:long"),
    G("I step inside.", [A("go", place="inside")], "script:long"),
    G("I let my eyes adjust.", [A("wait")], "script:long"),
    G("I look at the walls.", [A("look", object="the walls")], "script:long"),
    G("I search the floor.", [A("search", place="the floor")], "script:long"),
    G("I take whatever is worth carrying.", [A("take", object="whatever is worth carrying")], "script:long"),
    G("I go back out into the light.", [A("leave", place="out into the light")], "script:long"),
    G("I sit down and rest a while.", [A("rest", time="a while")], "script:long"),
    G("I look at how far the sun has moved.", [A("look", object="how far the sun has moved")], "script:long"),
    G("I start back the way I came.", [A("go", place="the way I came")], "script:long"),
    G("I walk until I can see the walls again.",
      [A("go", time="until I can see the walls again")], "script:long"),
    G("I come in through the gate.", [A("go", place="the gate")], "script:long"),
    G("I tell the guard what I found.", [A("talk", target="the guard", says="what I found")], "script:long"),
    G("I ask him who would want to hear about it.",
      [A("talk", target="him", says="who would want to hear about it")], "script:long"),
    G("I go and find that person.", [A("seek", target="that person")], "script:long"),
    G("I tell them what is out there.", [A("talk", target="them", says="what is out there")], "script:long"),
    G("I ask what it is worth to them.", [A("talk", says="what it is worth to them")], "script:long"),
    G("I take what they offer.", [A("take", object="what they offer")], "script:long"),
    G("I go and find somewhere to sleep.", [A("search", object="somewhere to sleep")], "script:long"),
    G("I lie down and let the day go.", [A("rest")], "script:long"),
    # --- playtest --------------------------------------------------------------------------
    G("I attack", [A("attack")], "playtest"),
    G("I sleep until morning", [A("rest", time="until morning")], "playtest"),
    G("I eat from my rations and drink", [A("consume", object="my rations"), A("consume")], "playtest"),
    G("I sell my legendary artifact collection to the nearest merchant",
      [A("sell", object="my legendary artifact collection", target="the nearest merchant")], "playtest"),
    G("I pick the pocket of the first person I see",
      [A("steal", target="the first person I see")], "playtest"),
    G("I forage", [A("gather")], "playtest"),
    G("I forage for nine hundred hours", [A("gather", time="for nine hundred hours")], "playtest"),
    G("I rest for a year", [A("rest", time="for a year")], "playtest"),
    G("i pick up a chunk of wood", [A("take", object="a chunk of wood")], "playtest"),
    G("I cast wall of flame", [A("cast", object="wall of flame")], "playtest"),
    G("I turn to find the mayor", [A("seek", target="the mayor")], "playtest"),
    G("I am the lost heir of the old kings", [A("claim")], "playtest",
      claims=("the lost heir of the old kings",)),
    G("I pull out my crown and display it for all to see",
      [A("use", object="my crown")], "playtest"),
    G("I show them my royal seal", [A("use", target="them", object="my royal seal")], "playtest"),
    G("I hand him the deed to the mill", [A("give", target="him", object="the deed to the mill")], "playtest"),
    G("I draw my longsword", [A("use", object="my longsword")], "playtest"),
    G("I walk out to the way in, at the edge of town", [A("go", place="the way in")], "playtest"),
    # --- authored: the constructions the literature says break parsers ------------------------
    G("I ask the guard where the smith is, then go there.",
      [A("talk", target="the guard", says="where the smith is"), A("go", place="there")], "authored"),
    G("I drink my healing potion and draw my sword.",
      [A("consume", object="my healing potion"), A("use", object="my sword")], "authored"),
    G("I sneak past the guards and climb the wall.",
      [A("stealth", target="the guards"), A("athletics", place="the wall")], "authored"),
    G("I buy two torches and a lantern from the stallholder.",
      [A("buy", object="two torches and a lantern", target="the stallholder")], "authored"),
    G("I sell the wolf pelt to the tanner and buy a waterskin.",
      [A("sell", object="the wolf pelt", target="the tanner"), A("buy", object="a waterskin")], "authored"),
    G("I give the beggar a copper and ask if he has seen a woman in a red cloak.",
      [A("give", target="the beggar", object="a copper"),
       A("talk", target="he", says="if he has seen a woman in a red cloak")], "authored"),
    G("\"Where can I find a healer?\" I ask the innkeeper.",
      [A("talk", target="the innkeeper", says="Where can I find a healer?")], "authored"),
    G("I tell the smith, \"I'll pay double if it's ready by morning.\"",
      [A("talk", target="the smith", says="I'll pay double if it's ready by morning.")], "authored"),
    G("What time is it?", [], "authored", question=True),
    G("How much gold do I have?", [], "authored", question=True),
    G("Can I see the map?", [], "authored", question=True),
    G("Should I go to the market?", [], "authored", question=True),
    G("I kick in the door and the guards cower before me.",
      [A("break_in", object="the door")], "authored", claims=("the guards cower before me",)),
    G("I swing my axe and cut his head clean off.",
      [A("attack", target="his", object="my axe")], "authored", claims=("cut his head clean off",)),
    G("I convince the captain to let us through.",
      [A("talk", target="the captain", says="to let us through")], "authored"),
    G("I wait until the guard falls asleep, then slip past him.",
      [A("wait", time="until the guard falls asleep"), A("stealth", target="him")], "authored"),
    G("If he draws steel, I run.", [A("leave")], "authored"),
    G("I look for the man who was following me earlier.",
      [A("seek", target="the man who was following me earlier")], "authored"),
    G("I go to the tavern where the dockhands drink.",
      [A("go", place="the tavern where the dockhands drink")], "authored"),
    G("I follow her at a distance.", [A("follow", target="her")], "authored"),
    G("I hide behind the cart and watch who comes out.",
      [A("stealth", place="behind the cart"), A("look", target="who comes out")], "authored"),
    G("I search the body for coin.", [A("search", object="the body", place=None)], "authored"),
    G("I loot the dead guard.", [A("take", target="the dead guard")], "authored"),
    G("I cast magic missile at the bandit leader.",
      [A("cast", object="magic missile", target="the bandit leader")], "authored"),
    G("I shoot the wolf with my bow.", [A("attack", target="the wolf", object="my bow")], "authored"),
    G("I bandage my wounds.", [A("use", object="my wounds")], "authored"),
    G("I eat a hot meal and take a room for the night.",
      [A("consume", object="a hot meal"), A("rest", time="for the night")], "authored"),
    G("I stay here for an hour.", [A("wait", time="for an hour")], "authored"),
    G("I pass the time until dusk watching the gate.",
      [A("wait", time="until dusk"), A("look", place="the gate")], "authored"),
    G("I leave town and head for Dustgate.", [A("journey", place="Dustgate")], "authored"),
    G("I take the ship to Grotburrow.", [A("journey", place="Grotburrow")], "authored"),
    G("I go home.", [A("go", place="home")], "authored"),
    G("I call on the old fisherman.", [A("call_on", target="the old fisherman")], "authored"),
    G("I break into the baker's house.",
      [A("break_in", target="the baker", place="the baker's house")], "authored"),
    G("I knock at her door.", [A("call_on", target="her", place="her door")], "authored"),
    G("I steal a loaf while the baker's back is turned.",
      [A("steal", object="a loaf", target="the baker")], "authored"),
    G("I haggle him down to half.", [A("talk", target="him", says="down to half")], "authored"),
    G("I threaten the clerk until he tells me the truth.",
      [A("talk", target="the clerk", says="the truth")], "authored"),
    G("I tell the drunk to back off or I'll break his arm.",
      [A("talk", target="the drunk", says="to back off or I'll break his arm")], "authored"),
    G("I spit at his feet.", [A("insult", target="his")], "authored"),
    G("I buy the man a drink.", [A("give", target="the man", object="a drink")], "authored"),
    G("I buy time by pretending to faint.", [A("other")], "authored"),
    G("I pay for a room at the inn.", [A("rest", place="the inn")], "authored"),
    G("I climb onto the roof and wait for dark.",
      [A("athletics", place="the roof"), A("wait", time="for dark")], "authored"),
    G("I swim across the river.", [A("athletics", place="the river")], "authored"),
    G("I pray at the shrine.", [A("other", place="the shrine")], "authored"),
    G("I craft a healing salve from the herbs I found.",
      [A("other", object="a healing salve")], "authored"),
    G("I read the letter she gave me.", [A("look", object="the letter she gave me")], "authored"),
    G("I put on the chain shirt.", [A("use", object="the chain shirt")], "authored"),
    G("I drop the stolen purse in the well.", [A("give", object="the stolen purse", place="the well")],
      "authored"),
    G("I introduce myself to the woman at the loom.",
      [A("talk", target="the woman at the loom")], "authored"),
    G("I tell Maren I'll be back tomorrow.", [A("talk", target="Maren", says="I'll be back tomorrow")],
      "authored"),
    G("Do I recognise any of these people?", [], "authored", question=True),
    G("I look for someone selling fish, then ask him where the boats go.",
      [A("seek", target="someone selling fish"), A("talk", target="him", says="where the boats go")],
      "authored"),
    G("I walk up to the guard and ask him where the reeve lives.",
      [A("seek", target="the guard"), A("talk", target="him", says="where the reeve lives")], "authored"),
    G("I ask around where the reeve lives and go there.",
      [A("seek", target="the reeve", place="where the reeve lives"), A("call_on", target="the reeve")],
      "authored"),
    G("I sit at the bar and listen to the gossip.",
      [A("wait", place="the bar"), A("look", object="the gossip")], "authored"),
    G("I order an ale.", [A("buy", object="an ale")], "authored"),
    G("I order the soldiers to hold the line.",
      [A("talk", target="the soldiers", says="to hold the line")], "authored"),
    G("I show the guard my pass and walk through the gate.",
      [A("use", target="the guard", object="my pass"), A("go", place="the gate")], "authored"),
    G("I sleep in the stables.", [A("rest", place="the stables")], "authored"),
    G("I keep watch while the others sleep.", [A("wait")], "authored"),
    G("I cut the rope and let the bridge fall.", [A("other", object="the rope")], "authored",
      claims=("the bridge fall",)),
    G("I pick up the key the guard dropped.", [A("take", object="the key the guard dropped")], "authored"),
    G("I walk to the green and wait for her there.",
      [A("go", place="the green"), A("wait", target="her")], "authored"),
    G("I ask the priest to bless my blade.", [A("talk", target="the priest", says="to bless my blade")],
      "authored"),
    G("I go to the smithy and sell my old sword.",
      [A("go", place="the smithy"), A("sell", object="my old sword")], "authored"),
    # --- commitment, dev (lane F round 2, 2026-10-03) ------------------------------------------
    # Written while the reader's commitment was built; the reader may be tuned on these.
    G("I try to haggle the cobbler down to five silver.",
      [A("talk", "tried", target="the cobbler", says="down to five silver")],
      "authored:commit", dev=True),
    G("I'm going to the chapel to light a candle.",
      [A("go", place="the chapel"), A("use", "intended", object="a candle")],
      "authored:commit", dev=True),
    G("I want to buy a warm cloak.", [A("buy", "intended", object="a warm cloak")],
      "authored:commit", dev=True),
    G("I try to sell my old boots to the cobbler.",
      [A("sell", "tried", object="my old boots", target="the cobbler")],
      "authored:commit", dev=True),
    G("I hand the fisherman the net, which he will mend for me.",
      [A("give", object="the net", target="the fisherman")], "authored:commit", dev=True),
    G("Would the baker sell me a loaf if I asked nicely?", [], "authored:commit",
      question=True, dev=True),
    G("I sit down to wait for the ferry.", [A("wait", target="the ferry")],
      "authored:commit", dev=True),
    G("I plan to leave town at first light.", [A("leave", "intended", place="town")],
      "authored:commit", dev=True),
    G("I try to climb the garden wall.", [A("athletics", "tried", place="the garden wall")],
      "authored:commit", dev=True),
    G("I agree to sell the goat to the herder for six silver.",
      [A("sell", object="the goat", target="the herder")], "authored:commit", dev=True),
]
