"""The means corpus: deeds a character has no means to do, and deeds anybody may try.

Written 2026-10-05 for gm/means.py, before any reading of these lines was seen. Two
sheets, both shipped fixtures: `kesst` (fixtures/pc-kesst.json, a level-1 human rogue —
rapier, dagger, Weapon Finesse, Stealthy, no spells) and `ysolde`
(fixtures/pc-caster.json, a level-1 human wizard whose book holds Sleep, Color Spray,
Daze, Mage Hand, Message, Ghost Sound and the rest of the cantrips, and no Charm Person,
no Fly, no Fireball).

Each row is (line, sheet, expect):
  refuse  nothing the sheet holds does this, and no ordinary person could
  pass    an ordinary attempt (the dice or the other person decide), or a power held
  claim   an ordinary attempt with its RESULT declared — passes, and the result must come
          back as the reading's claim, never as a fact or a means

None of these is a demonstration in gm/interpret.py or gm/means.py; the demonstrations
were written first and kept apart (`test_no_corpus_line_is_a_demonstration`).

`DEV` is what the first pass was measured on. `HELD_OUT` was written after the first
pass's numbers were in and before any fix that followed (docs/means-gate.md).
"""

REFUSE, PASS, CLAIM = "refuse", "pass", "claim"

DEV = [
    # --- minds and memories ---------------------------------------------------------
    ("I read the innkeeper's mind", "kesst", REFUSE),
    ("I listen to the guard's thoughts", "kesst", REFUSE),
    ("I slip into the merchant's head and see what he's hiding", "kesst", REFUSE),
    ("I make the guard forget he saw me", "kesst", REFUSE),
    ("I wipe the clerk's memory of our deal", "kesst", REFUSE),
    ("I make the baker remember me as an old friend", "kesst", REFUSE),
    ("I put the idea of opening the gate into the sentry's head", "kesst", REFUSE),
    ("I will the captain to obey me", "kesst", REFUSE),
    ("I order the guard to kneel with a thought", "kesst", REFUSE),
    ("I send my thoughts to my sister across town", "kesst", REFUSE),
    ("I make the smith fall asleep just by looking at him", "kesst", REFUSE),
    ("I fill the thug's mind with terror with a glance", "kesst", REFUSE),
    ("I take control of the ogre's body", "kesst", REFUSE),
    ("I pull the combination of the lock out of the locksmith's head", "kesst", REFUSE),
    ("I look through the merchant's memories of last night", "kesst", REFUSE),
    ("I make the whole tavern forget the fight happened", "kesst", REFUSE),
    # --- the body of the world ------------------------------------------------------
    ("I teleport to the top of the tower", "kesst", REFUSE),
    ("I blink across the river", "kesst", REFUSE),
    ("I fly over the city wall", "kesst", REFUSE),
    ("I float up to the balcony", "kesst", REFUSE),
    ("I walk through the wall into the vault", "kesst", REFUSE),
    ("I turn invisible and slip past the guards", "kesst", REFUSE),
    ("I phase through the locked door", "kesst", REFUSE),
    ("I lift the cart with my mind", "kesst", REFUSE),
    ("I pull the sword from his hand without touching it", "kesst", REFUSE),
    ("I stop time and take the purse", "kesst", REFUSE),
    # --- making things ---------------------------------------------------------------
    ("I conjure a bag of gold", "kesst", REFUSE),
    ("I make a sword appear in my hand", "kesst", REFUSE),
    ("I summon a wolf pack to attack the bandits", "kesst", REFUSE),
    ("I create a horse out of thin air", "kesst", REFUSE),
    ("I pull a hot meal out of nowhere", "kesst", REFUSE),
    ("I make the empty chest fill with jewels", "kesst", REFUSE),
    ("I raise the dead guard as my servant", "kesst", REFUSE),
    ("I call a dragon down from the mountains to fight for me", "kesst", REFUSE),
    # --- weather and land ------------------------------------------------------------
    ("I make it rain", "kesst", REFUSE),
    ("I call down lightning on the bandit", "kesst", REFUSE),
    ("I part the river so I can walk across", "kesst", REFUSE),
    ("I calm the storm with a wave of my hand", "kesst", REFUSE),
    ("I make the sun set early", "kesst", REFUSE),
    ("I cause an earthquake under the fort", "kesst", REFUSE),
    # --- changing shape --------------------------------------------------------------
    ("I turn into a wolf", "kesst", REFUSE),
    ("I change my face to look exactly like the captain", "kesst", REFUSE),
    ("I grow wings and fly away", "kesst", REFUSE),
    ("I turn the guard into a frog", "kesst", REFUSE),
    ("I turn the iron bars into butter", "kesst", REFUSE),
    ("I turn the lead pipe into gold", "kesst", REFUSE),
    # --- bodies beyond a body --------------------------------------------------------
    ("I heal my wounds instantly by concentrating", "kesst", REFUSE),
    ("I lay my hands on the dying man and heal him", "kesst", REFUSE),
    ("I regrow my missing finger", "kesst", REFUSE),
    ("I bring the dead girl back to life", "kesst", REFUSE),
    ("I breathe fire at the goblins", "kesst", REFUSE),
    ("I make my skin hard as steel", "kesst", REFUSE),
    # --- knowing what cannot be known ------------------------------------------------
    ("I know exactly where the bandit camp is", "kesst", REFUSE),
    ("I sense who killed the mayor", "kesst", REFUSE),
    ("I see the future of this town", "kesst", REFUSE),
    ("I look through the wall to see who is inside", "kesst", REFUSE),
    ("I hear what they are saying three streets away", "kesst", REFUSE),
    ("I instantly learn to speak Draconic", "kesst", REFUSE),
    # --- deciding what is true, or what others feel ----------------------------------
    ("I decide that the smith owes me fifty gold", "kesst", REFUSE),
    ("I make the merchant love me", "kesst", REFUSE),
    ("I make the whole market bow to me", "kesst", REFUSE),
    ("I erase the bounty on my head from existence", "kesst", REFUSE),
    ("I make the guards my loyal servants", "kesst", REFUSE),
    ("I command the river to carry me downstream", "kesst", REFUSE),
    ("I make the lock open by touching it", "kesst", REFUSE),
    ("I make the guard drop his spear with a word of power", "kesst", REFUSE),
    ("I control the horses with my mind", "kesst", REFUSE),
    # --- powers named that the sheet does not hold -----------------------------------
    ("I cast fireball at the bandits", "kesst", REFUSE),
    ("I cast charm person on the guard", "kesst", REFUSE),
    ("I cast cure light wounds on myself", "kesst", REFUSE),
    ("I use my rage to break the door", "kesst", REFUSE),
    ("I use lay on hands on the farmer", "kesst", REFUSE),
    ("I channel positive energy to heal everyone", "kesst", REFUSE),
    ("I use smite evil on the cultist", "kesst", REFUSE),
    ("I wild shape into a bear", "kesst", REFUSE),
    ("I use my wand of lightning on the troll", "kesst", REFUSE),
    ("I drink my potion of flying", "kesst", REFUSE),
    ("I put on my ring of invisibility", "kesst", REFUSE),
    ("I use my psychic powers to calm the crowd", "kesst", REFUSE),
    ("I unleash my divine power on the bandits", "kesst", REFUSE),
    ("I use telepathy to ask the guard where the key is", "kesst", REFUSE),
    ("I cast fireball at the bandits", "ysolde", REFUSE),
    ("I cast charm person on the guard", "ysolde", REFUSE),
    ("I cast fly on myself", "ysolde", REFUSE),
    ("I read the guard's mind", "ysolde", REFUSE),
    ("I teleport home", "ysolde", REFUSE),
    ("I cast dominate person on the captain", "ysolde", REFUSE),

    # --- talking, lying, leaning on people -------------------------------------------
    ("I convince the guard I was never here", "kesst", PASS),
    ("I tell the guard he never saw me and slip him a coin", "kesst", PASS),
    ("I persuade the innkeeper to give me a room for free", "kesst", PASS),
    ("I lie to the captain about where I was last night", "kesst", PASS),
    ("I threaten the thug with my dagger until he backs off", "kesst", PASS),
    ("I bribe the clerk to forget the paperwork", "kesst", PASS),
    ("I flatter the merchant to get a better price", "kesst", PASS),
    ("I tell the smith I'm his cousin from the hills", "kesst", PASS),
    ("I spin a story that I'm the mayor's nephew", "kesst", PASS),
    ("I plead with the judge for mercy", "kesst", PASS),
    ("I flirt with the barmaid", "kesst", PASS),
    ("I ask the baker what she remembers about last night", "kesst", PASS),
    ("I remind the guard that he owes me a favour", "kesst", PASS),
    ("I make the guard laugh with a joke", "kesst", PASS),
    ("I distract the clerk with small talk", "kesst", PASS),
    ("I calm the frightened child with soft words", "kesst", PASS),
    ("I intimidate the bandit into telling me where the camp is", "kesst", PASS),
    ("I haggle the price of the rope down", "kesst", PASS),
    ("I talk the guard into letting me through", "kesst", PASS),
    ("I give a rousing speech to the crowd", "kesst", PASS),
    # --- reading people and pages ----------------------------------------------------
    ("I watch the innkeeper's face to see if she's lying", "kesst", PASS),
    ("I study the merchant's body language", "kesst", PASS),
    ("I guess what the guard is thinking from his expression", "kesst", PASS),
    ("I try to read the room", "kesst", PASS),
    ("I read the letter on the desk", "kesst", PASS),
    ("I read the merchant's ledger", "kesst", PASS),
    ("I try to tell if the stranger means me harm", "kesst", PASS),
    # --- one's own mind --------------------------------------------------------------
    ("I try to remember where I've seen him before", "kesst", PASS),
    ("I think about what the old man told me", "kesst", PASS),
    ("I clear my mind and focus", "kesst", PASS),
    ("I make up my mind to head north", "kesst", PASS),
    ("I recall the map of the sewers", "kesst", PASS),
    # --- bodies and things -----------------------------------------------------------
    ("I climb the wall", "kesst", PASS),
    ("I leap over the cart", "kesst", PASS),
    ("I swim across the river", "kesst", PASS),
    ("I hide behind the barrels", "kesst", PASS),
    ("I sneak past the sleeping guard", "kesst", PASS),
    ("I pick the lock on the chest", "kesst", PASS),
    ("I punch the thug in the jaw", "kesst", PASS),
    ("I stab the bandit with my rapier", "kesst", PASS),
    ("I throw my dagger at the rat", "kesst", PASS),
    ("I kick the door open", "kesst", PASS),
    ("I grab the purse off the table", "kesst", PASS),
    ("I tie up the prisoner", "kesst", PASS),
    ("I disarm the guard", "kesst", PASS),
    ("I shove the drunk out of the way", "kesst", PASS),
    ("I run to the gate", "kesst", PASS),
    ("I bandage my wounds", "kesst", PASS),
    ("I search the room for hidden doors", "kesst", PASS),
    ("I listen at the door", "kesst", PASS),
    ("I look out over the harbour", "kesst", PASS),
    ("I cook a meal over the fire", "kesst", PASS),
    ("I sharpen my rapier", "kesst", PASS),
    ("I light a torch", "kesst", PASS),
    ("I break the window with my elbow", "kesst", PASS),
    ("I lift the heavy crate", "kesst", PASS),
    ("I pull the lever", "kesst", PASS),
    ("I wait until nightfall", "kesst", PASS),
    ("I sleep at the inn", "kesst", PASS),
    ("I buy bread from the baker", "kesst", PASS),
    ("I sell my old cloak", "kesst", PASS),
    ("I give the beggar a coin", "kesst", PASS),
    ("I pick the merchant's pocket", "kesst", PASS),
    ("I follow the man in the grey hood", "kesst", PASS),
    ("I track the deer through the woods", "kesst", PASS),
    ("I forage for herbs", "kesst", PASS),
    ("I disguise myself as a dock worker", "kesst", PASS),
    ("I pretend to be a guard", "kesst", PASS),
    ("I sing a song for the tavern", "kesst", PASS),
    ("I tame the stray dog with some scraps", "kesst", PASS),
    ("I scare off the crows by shouting", "kesst", PASS),
    ("I make a torch from a branch and some rags", "kesst", PASS),
    ("I set a snare for rabbits", "kesst", PASS),
    # --- powers the sheet holds ------------------------------------------------------
    ("I cast sleep on the guards", "ysolde", PASS),
    ("I cast color spray at the bandits", "ysolde", PASS),
    ("I cast daze on the thug", "ysolde", PASS),
    ("I cast mage hand to lift the key off the hook", "ysolde", PASS),
    ("I cast message and whisper to my friend across the room", "ysolde", PASS),
    ("I cast magic missile at the goblin", "ysolde", PASS),
    ("I cast detect magic on the chest", "ysolde", PASS),
    ("I cast prestidigitation to clean my robes", "ysolde", PASS),
    ("I put the guard to sleep with my sleep spell", "ysolde", PASS),
    ("I cast light on my staff", "ysolde", PASS),
    ("I cast mending on the torn sail", "ysolde", PASS),
    ("I use mage hand to pull the lever", "ysolde", PASS),
    ("I cast ghost sound to make the guards think someone is behind them", "ysolde", PASS),
    ("I cast shield", "ysolde", PASS),
    ("I cast ray of frost at the wolf", "ysolde", PASS),
    ("I hit the skeleton with my quarterstaff", "ysolde", PASS),

    # --- a result declared with the attempt ------------------------------------------
    ("I lie to the guard and he believes every word", "kesst", CLAIM),
    ("I punch the thug and knock him out cold", "kesst", CLAIM),
    ("I flirt with the barmaid and she falls for me", "kesst", CLAIM),
    ("I pick the lock and the door swings open", "kesst", CLAIM),
    ("I persuade the merchant and he gives me the sword for free", "kesst", CLAIM),
    ("I stab the bandit and kill him", "kesst", CLAIM),
    ("I bribe the guard and he lets me in", "kesst", CLAIM),
    ("I threaten the clerk and he hands over the keys", "kesst", CLAIM),
    ("I search the room and find the hidden key", "kesst", CLAIM),
]

# Written after the first pass's numbers (docs/means-gate.md); no fix was made from them.
HELD_OUT = [
    ("I peek inside the bartender's thoughts", "kesst", REFUSE),
    ("I make the clerk forget I ever came in", "kesst", REFUSE),
    ("I give the widow a false memory of her husband's debt", "kesst", REFUSE),
    ("I scrub the last hour from the watchman's memory", "kesst", REFUSE),
    ("I whisper into the sergeant's mind to let me pass", "kesst", REFUSE),
    ("I make the bandit leader trust me completely with a snap of my fingers", "kesst",
     REFUSE),
    ("I bend the priest to my will", "kesst", REFUSE),
    ("I hypnotise the gatekeeper", "kesst", REFUSE),
    ("I know what the merchant is thinking", "kesst", REFUSE),
    ("I make the crowd feel hopeless", "kesst", REFUSE),
    ("I appear behind the bandit in a puff of smoke", "kesst", REFUSE),
    ("I jump to the moon", "kesst", REFUSE),
    ("I hover over the pit", "kesst", REFUSE),
    ("I squeeze myself through the keyhole", "kesst", REFUSE),
    ("I fade out of sight in the middle of the square", "kesst", REFUSE),
    ("I shatter the door with a shout", "kesst", REFUSE),
    ("I fling the guards across the room without touching them", "kesst", REFUSE),
    ("I freeze the river solid with a touch", "kesst", REFUSE),
    ("I make a rope appear out of nowhere", "kesst", REFUSE),
    ("I produce a key to the vault from thin air", "kesst", REFUSE),
    ("I call a swarm of bees to sting the guard", "kesst", REFUSE),
    ("I bring the stone statue to life", "kesst", REFUSE),
    ("I make the wind push our boat faster", "kesst", REFUSE),
    ("I make night fall right now", "kesst", REFUSE),
    ("I make the forest grow over the road", "kesst", REFUSE),
    ("I shapeshift into a hawk", "kesst", REFUSE),
    ("I take on the appearance of the duke by magic", "kesst", REFUSE),
    ("I shrink myself to the size of a mouse", "kesst", REFUSE),
    ("I turn my rapier into a flaming sword", "kesst", REFUSE),
    ("I mend my broken arm with a thought", "kesst", REFUSE),
    ("I cure the whole village of the plague", "kesst", REFUSE),
    ("I spit acid at the guard", "kesst", REFUSE),
    ("I sense the treasure buried under the floor", "kesst", REFUSE),
    ("I see through the guard's eyes", "kesst", REFUSE),
    ("I already know the duke's secret plans", "kesst", REFUSE),
    ("I declare that I am now the mayor of this town", "kesst", REFUSE),
    ("I make it so the bandits never attacked the caravan", "kesst", REFUSE),
    ("I make the shopkeeper give me everything for free just by asking", "kesst", REFUSE),
    ("I cast magic missile at the goblin", "kesst", REFUSE),
    ("I cast bless on my companions", "kesst", REFUSE),
    ("I use my sneak attack aura to stun everyone", "kesst", REFUSE),
    ("I use my cloak of flying to escape", "kesst", REFUSE),
    ("I read the scroll of fireball at them", "kesst", REFUSE),
    ("I cast invisibility on myself", "ysolde", REFUSE),
    ("I cast haste on my allies", "ysolde", REFUSE),
    ("I make the innkeeper forget my face", "ysolde", REFUSE),
    ("I conjure a feast for the beggars", "ysolde", REFUSE),

    ("I try to convince the watchman that I live here", "kesst", PASS),
    ("I tell the clerk I'm a royal inspector", "kesst", PASS),
    ("I warn the thug that my friends are watching", "kesst", PASS),
    ("I bribe the gatekeeper with five silver to look the other way", "kesst", PASS),
    ("I sweet-talk the cook into an extra helping", "kesst", PASS),
    ("I beg the priest to hide me", "kesst", PASS),
    ("I stare down the bully", "kesst", PASS),
    ("I ask the widow if she remembers who visited her husband", "kesst", PASS),
    ("I convince the smith he must have misremembered the price", "kesst", PASS),
    ("I watch the gambler's hands for a cheat", "kesst", PASS),
    ("I try to figure out what the bartender wants", "kesst", PASS),
    ("I size up the stranger", "kesst", PASS),
    ("I think back to the night of the fire", "kesst", PASS),
    ("I keep my thoughts to myself", "kesst", PASS),
    ("I scale the cliff", "kesst", PASS),
    ("I vault the fence", "kesst", PASS),
    ("I wade across the stream", "kesst", PASS),
    ("I slip into the crowd and lose my pursuers", "kesst", PASS),
    ("I creep up behind the sentry", "kesst", PASS),
    ("I jimmy the window open with my dagger", "kesst", PASS),
    ("I headbutt the drunk", "kesst", PASS),
    ("I slash at the wolf with my rapier", "kesst", PASS),
    ("I trip the fleeing thief", "kesst", PASS),
    ("I barricade the door with a table", "kesst", PASS),
    ("I wrestle the knife out of his hand", "kesst", PASS),
    ("I hide the coins in my boot", "kesst", PASS),
    ("I count my money", "kesst", PASS),
    ("I set up camp by the river", "kesst", PASS),
    ("I fish in the stream", "kesst", PASS),
    ("I mend my torn cloak with needle and thread", "kesst", PASS),
    ("I put on a fake accent", "kesst", PASS),
    ("I play dead", "kesst", PASS),
    ("I feed the horse an apple", "kesst", PASS),
    ("I pour the ale over his head", "kesst", PASS),
    ("I cast daze on the drunk", "ysolde", PASS),
    ("I put the bandits to sleep", "ysolde", PASS),
    ("I cast flare in the guard's eyes", "ysolde", PASS),
    ("I cast open/close on the shutters", "ysolde", PASS),
    ("I cast read magic on the scroll", "ysolde", PASS),
    ("I use mage armor before the fight", "ysolde", PASS),
    ("I cast acid splash at the slime", "ysolde", PASS),

    ("I shove the guard and he tumbles down the stairs", "kesst", CLAIM),
    ("I sneak past the dogs and they never notice me", "kesst", CLAIM),
    ("I haggle with the smith and he halves the price", "kesst", CLAIM),
    ("I tell the guard a sob story and he lets me go", "kesst", CLAIM),
    ("I throw my dagger and hit him right between the eyes", "kesst", CLAIM),
]
