"""Writes docs/alchemy-review.md: the alchemy data pass laid out for the owner.

Generated from the data, so the page cannot drift from it:

    python tools/alchemy_review.py           # write the page
    python tools/alchemy_review.py --check   # exit 1 if the page is stale

Every number on the page is computed here from the shipped files (the materials, the
potions, the herb corpus) through the same functions the game uses: `effectspec.render`
for a trait's words, `pricing.worth` for what a thing is worth, `materials.alchemy_shelf`
for what sits on the shelf. The "before" columns read the commit lane D branched from
(`BEFORE`) through git; without git they are left out and say so.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "pathfindergm.settings")

import django  # noqa: E402

django.setup()

from rules import effectspec, materials, pricing  # noqa: E402

sys.path.insert(0, str(ROOT / "tools"))
from alchemy_essence import essence_of  # noqa: E402

OUT = ROOT / "docs" / "alchemy-review.md"
BEFORE = "3bbd361"   # build/alchemy at the start of lane D (2026-10-06)
TIERS = ("common", "uncommon", "rare", "exotic", "legendary")

# The owner's flag for a Transmute pair (open point 10, 2026-10-06): the output worth more
# than three times what goes in.
TRANSMUTE_FLAG = 3.0
# What the book says the raw materials of a made thing cost: a third of an alchemical
# item's price (Craft, CRB) and half of a potion's (Brew Potion, CRB) — plan §5.9.
CRAFT_FRACTION = 1 / 3
POTION_FRACTION = 1 / 2

# The classics' book prices, read 2026-10-06 from the AoN pages named, and the material
# sets the catalogue's recipe table (docs/alchemy.md, "The classic-output recipe table")
# makes them from. Lane E's formula table replaces the material sets with essence
# requirements; until it lands these are the sets a player can actually buy.
AON_WEAPONS = "https://www.aonprd.com/EquipmentMisc.aspx?Category=AlchemicalWeapons"
AON_REMEDIES = "https://aonprd.com/EquipmentMisc.aspx?Category=AlchemicalRemedies"
AON_TOOLS = "https://www.aonprd.com/EquipmentMisc.aspx?Category=AlchemicalTools"
CLASSICS = [
    ("Alchemist's fire", 20, AON_WEAPONS, ["brimstone", "naphtha", "clay-flask"]),
    ("Acid flask", 10, AON_WEAPONS, ["oil-of-vitriol", "lead-glass-vial"]),
    ("Tanglefoot bag", 50, AON_WEAPONS,
     ["pine-pitch", "giant-frog-mucus", "turpentine", "waxed-bladder"]),
    ("Thunderstone", 30, AON_WEAPONS,
     ["storm-quartz", "saltpetre", "distilled-water", "brass-casing"]),
    ("Smokestick", 20, AON_TOOLS, ["smoke-resin", "lamp-black", "saltpetre",
                                   "distilled-water"]),
    ("Tindertwig", 1, AON_TOOLS, ["phosphorus", "brimstone", "turpentine"]),
    ("Sunrod", 2, AON_TOOLS, ["fire-beetle-gland", "phosphorus", "distilled-water"]),
    ("Antitoxin", 50, AON_REMEDIES,
     ["adder-venom-gland", "willow-charcoal", "bitter-aloes", "white-vinegar"]),
    ("Antiplague", 50, AON_REMEDIES, ["silver-salt", "camphor", "distilled-water"]),
    ("Alchemical grease", 5, AON_REMEDIES, ["slick-jelly", "tallow", "turpentine"]),
    ("Itching powder", 60, AON_WEAPONS, ["itchweed-floss"]),
    ("Alkali flask", 15, AON_WEAPONS, ["quicklime", "brine"]),
    ("Liquid ice", 40, AON_WEAPONS, ["everfrost-salt", "distilled-water"]),
    ("Flash powder", 50, AON_WEAPONS, ["phosphorus", "saltpetre", "strong-spirits"]),
    ("Smelling salts", 25, AON_REMEDIES, ["sal-volatile", "sal-ammoniac"]),
    ("Vermin repellent", 5, AON_REMEDIES, ["camphor", "skunk-musk-gland", "tallow"]),
    ("Bladeguard", 40, AON_REMEDIES, ["verdigris", "beeswax", "turpentine"]),
    ("Holy weapon balm", 30, AON_WEAPONS,
     ["saints-tallow", "sunmetal-filings", "rectified-spirits"]),
]

HEAD = """# Alchemy: the data pass, for review

Generated by `tools/alchemy_review.py` from `content/materials/alchemist-materials.json`,
`content/materials/alchemist-spell-potions.json` and the hybrid herbs in
`content/ingredients/herbs-and-parts.json`; do not edit by hand (run the tool after changing
the data; `--check` says whether this page is stale). The numbers are written by
`tools/alchemy_data_pass.py`, which validates every row (`materials.alchemy_problems`, the
price rule, the vocabulary) before it writes.

How to read it:

- **Product traits** are what a material puts into a bottle: a typed effect, the **route**
  it reaches a body by (struck: the creature a thrown flask hits; area: everyone in a
  cloud; ingest: whoever drinks it; skin, eyes, inhale; external: a coating or a light;
  carried: whoever holds it) and its **essence** in brackets, the tag a formula keys on.
  Every house trait starts at grade 1; the bench adds grades. **Drawbacks are in bold**:
  a cost to whoever uses the product, carried into it with any benefit from the same
  material and stripped by Filter.
- **Working traits** are how it behaves at the bench and never reach the product.
  **Mishap** is what a roll failed by 5 or more does to the alchemist (volatile inputs
  only); **toxic** is what working it without a mask and gloves or a fume hood does.
- **Book** traits are printed numbers, cited, and not offered for tuning. Everything else is
  this pass's house draft for your judgment, held inside the ceilings in "The fences".
- A material with no product traits is **apparatus**: a vessel, a catalyst that is never
  spent, a neutral medium or the wild prima materia. It works at the bench and carries
  nothing into the bottle, so it needs three working properties and no drawback (your
  Q7.1 ruling reads "per reagent").
"""


def _render(spec: dict) -> str:
    words = effectspec.render(spec)
    if spec.get("type") == "save_gate" and spec.get("on_failure") and "fail" not in words:
        inner = "; ".join(effectspec.render(e) for e in spec["on_failure"])
        words = f"{words}: {inner}"
    words = " ".join(str(words).split()).replace("|", "/")
    return words


def _trait(spec: dict) -> str:
    bits = f"{_render(spec)} ({spec.get('route', 'ingest')}) [{spec.get('essence', '?')}]"
    if spec.get("book"):
        bits += " *book*"
    return f"**{bits}**" if spec.get("drawback") else bits


def _old(path: str):
    try:
        raw = subprocess.run(["git", "show", f"{BEFORE}:{path}"], cwd=ROOT,
                             capture_output=True, check=True).stdout
        return json.loads(raw.decode("utf-8"))
    except Exception:  # noqa: BLE001 - no git, no history: the section says so
        return None


def _gp(value) -> str:
    if value is None:
        return "unpriced"
    return f"{value:,.2f}".rstrip("0").rstrip(".") + " gp"


def _cost(ids: list[str], shelf: dict) -> tuple[float | None, list[str]]:
    """What the spent inputs of a recipe cost to buy, and which inputs have no price.
    Catalysts and apparatus are never spent, so they cost nothing per batch."""
    total, unpriced = 0.0, []
    for mid in ids:
        doc = shelf.get(mid)
        if doc is None:
            unpriced.append(f"{mid} (not on the shelf)")
            continue
        traits = {str(w.get("trait")) for w in doc.get("working") or []}
        if traits & {"catalyst", "apparatus"}:
            continue
        price = doc.get("price_gp")
        if price in (None, "", 0):
            unpriced.append(mid)
            continue
        total += float(price)
    return total, unpriced


def _benefits(doc: dict) -> set[str]:
    """The essences a material's benefit traits carry (its drawbacks' left out)."""
    return {str(t["essence"]) for t in doc.get("product") or ()
            if t.get("essence") and not t.get("drawback")}


def _worth(doc: dict) -> float:
    return pricing.worth(doc)


def build() -> str:
    raw = json.loads((ROOT / "content/materials/alchemist-materials.json")
                     .read_text(encoding="utf-8"))["materials"]
    pots = json.loads((ROOT / "content/materials/alchemist-spell-potions.json")
                      .read_text(encoding="utf-8"))["potions"]
    shelf = materials.alchemy_shelf()
    docs = [shelf[r["id"]] for r in raw]
    lines = [HEAD]

    # --- counts
    traits = [t for d in docs for t in d["product"]]
    with_product = [d for d in docs if d["product"]]
    lines.append("## The counts\n")
    lines.append(f"- **{len(docs)} materials**: {len(with_product)} carry product traits "
                 f"({len(traits)} traits, {sum(1 for t in traits if t.get('drawback'))} of "
                 f"them drawbacks); {len(docs) - len(with_product)} are apparatus, media or "
                 f"wild.")
    lines.append(f"- Every material has at least 3 properties (fewest: "
                 f"{min(len(d['product']) + len(d['working']) + bool(d['mishap']) + bool(d['toxic']) for d in docs)}); "
                 f"{sum(1 for d in docs if d['mishap'])} carry a mishap, "
                 f"{sum(1 for d in docs if d['toxic'])} a toxic document, "
                 f"{sum(1 for d in docs if d.get('book'))} a book trait.")
    by_ess = Counter(t["essence"] for t in traits)
    by_route = Counter(t["route"] for t in traits)
    lines.append("- **By essence** (product traits): " + ", ".join(
        f"{e} {by_ess.get(e, 0)}" for e in effectspec.ESSENCES) + ".")
    lines.append("- **By route**: " + ", ".join(f"{r} {n}" for r, n in
                                                 sorted(by_route.items())) + ".")
    work = Counter(str(w["trait"]) for d in docs for w in d["working"])
    lines.append("- **Working traits**: " + ", ".join(f"{t} {n}" for t, n in
                                                      sorted(work.items())) + ".")
    hybrids = [d for d in shelf.values() if d.get("hybrid")]
    h_traits = [t for d in hybrids for t in d["product"]]
    h_ess = Counter(t.get("essence") for t in h_traits)
    lines.append(f"- **Hybrid herbs**: {len(hybrids)} on the shelf, {len(h_traits)} effects, "
                 f"each given an essence by the same rule: " + ", ".join(
                     f"{e} {h_ess.get(e, 0)}" for e in effectspec.ESSENCES if h_ess.get(e))
                 + ".")
    lines.append("")

    # --- fences
    lines.append("## The fences\n")
    lines.append("What `materials.alchemy_problems` refuses (plan §5.6), each with the fix "
                 "named:\n")
    lines.append("- fewer than 3 properties (product, working, mishap, toxic);")
    lines.append("- a material with product traits and no drawback (judged by "
                 "`knowledge.classify`, the card's own judge);")
    lines.append("- a product trait with no essence or route, a narrative one, or one the "
                 "engine cannot run and no reader is promised for;")
    lines.append("- a drawback on a foe's route (struck, splash, area);")
    lines.append("- a working trait the alchemist's bench does not know;")
    lines.append("- `volatile` without a mishap, a mishap without `volatile`, "
                 "`toxic_to_handle` without a toxic document and the other way round;")
    lines.append("- apparatus with no job (no vessel trait, solvent, stabilizer, catalyst or "
                 "apparatus);")
    lines.append("- a house number over its tier's ceiling. Flat numbers (bonuses, "
                 "resistance, fast healing) use the forge's ceilings; dice use the proposed "
                 "dice ceiling, compared by the largest roll:\n")
    lines.append("| Tier | Flat | Largest house die |")
    lines.append("|---|---|---|")
    for t in TIERS:
        lines.append(f"| {t} | ±{materials.TIER_CEILING[t]} | "
                     f"{materials.ALCHEMY_DICE_CEILING[t]} |")
    lines.append("")

    # --- what moved
    old = _old("content/materials/alchemist-materials.json")
    lines.append("## Numbers this pass changed\n")
    if old is None:
        lines.append("(git is not available here, so the before column cannot be read.)\n")
    else:
        lines.append("Every material whose pre-revamp effects differ from what it puts in a "
                     "bottle now: a number trimmed to its fence, a narrative line typed, the "
                     "handler's tax moved to the bench, a drawback or a second trait added. "
                     "Materials whose old list was empty are not here (all their traits are "
                     "new; see the tables below). The old list stays in the file as "
                     "`effects` for the old chain bench until it retires; nothing new reads "
                     "it.\n")
        lines.append("| Material | Tier | Before (`effects`) | Now (`product`, `toxic`) |")
        lines.append("|---|---|---|---|")
        before = {m["id"]: m for m in old["materials"]}
        for d in docs:
            was = before.get(d["id"], {}).get("effects") or []
            if not was:
                continue
            now = d["product"]
            was_words = "; ".join(_render(e) for e in was)
            now_words = "; ".join(_render(e) for e in now) or "(none)"
            if d.get("toxic"):
                now_words += f"; toxic: {_render(d['toxic'])}"
            if was_words != "; ".join(_render(e) for e in now):
                lines.append(f"| {d['name']} | {d['tier']} | {was_words} | {now_words} |")
        lines.append("")

    # --- the materials
    lines.append("## The materials\n")
    for tier in TIERS:
        rows = [d for d in docs if d["tier"] == tier]
        lines.append(f"### {tier.title()} ({len(rows)})\n")
        lines.append("| Material | Kind | Price | Product traits | Working | Mishap / toxic |")
        lines.append("|---|---|---|---|---|---|")
        for d in sorted(rows, key=lambda x: (x["kind"], x["name"])):
            prod = "<br>".join(_trait(t) for t in d["product"]) or "(apparatus)"
            work_words = ", ".join(
                str(w["trait"]) + (f" ({w['note']})" if w.get("note") else "")
                for w in d["working"])
            risk = []
            if d["mishap"]:
                risk.append("mishap: " + _render(d["mishap"]))
            if d["toxic"]:
                risk.append("toxic: " + _render(d["toxic"]))
            lines.append(f"| {d['name']} | {d['kind']} | {_gp(d.get('price_gp') or None)} | "
                         f"{prod} | {work_words} | {'<br>'.join(risk) or '-'} |")
        lines.append("")

    # --- book sources
    lines.append("## Book traits and their sources\n")
    for d in docs:
        if d.get("book"):
            rawrow = next(r for r in raw if r["id"] == d["id"])
            src = "; ".join(rawrow.get("book_source") or [])
            words = "; ".join(_render(t) for t in d["product"] if t.get("book"))
            lines.append(f"- **{d['name']}**: {words}. {src}")
    lines.append("- The book's poisons run 1/round for 6 rounds (10 for the linnorm) until "
                 "cured by consecutive saves; a save gate here is one application, because "
                 "no reader runs a poison's frequency yet. That is an open row below.")
    lines.append("")

    # --- the potions
    old_p = _old("content/materials/alchemist-spell-potions.json")
    lines.append("## The 44 potions: the narrative lines typed (plan §16.9)\n")
    lines.append("Ids, spells, caster levels and materials are unchanged (your Q10.2). "
                 "Each narrative line became the typed document on the right, or was "
                 "dropped where the potion's other lines already carry it. The essence "
                 "column is what the potion's typed lines read as by the essence rule, "
                 "against what its old materials' benefit traits carry: lane E's formula requirements "
                 "need the old recipe to still make the potion.\n")
    lines.append("| Potion | Narrative before | Typed now | Potion essences | "
                 "Its materials carry |")
    lines.append("|---|---|---|---|---|")
    before_p = {p["id"]: p for p in (old_p or {}).get("potions", [])}
    for p in pots:
        was = [e for e in before_p.get(p["id"], {}).get("effects", [])
               if e.get("type") == "narrative"]
        kept = [e for e in before_p.get(p["id"], {}).get("effects", [])
                if e.get("type") != "narrative"]
        new = [e for e in p["effects"] if e not in kept]
        skills = [e for e in new if e.get("type") == "skill_mod"]
        if len(skills) > 4:
            # Heroism's one line per skill (the vocabulary has no "every skill"), said once.
            s = skills[0]
            typed = [f"{s['amount']:+d} {s['bonus_type']} on each of the {len(skills)} "
                     f"skills"] + [_render(e) for e in new if e not in skills]
        else:
            typed = [_render(e) for e in new]
        if was and not typed:
            typed = ["dropped: the potion's other lines already carry it"]
        pe = sorted({essence_of(e) for e in p["effects"]})
        me = sorted({e for m in p["materials"] for e in _benefits(shelf.get(m) or {})})
        cover = "" if set(pe) & set(me) else " **(not covered)**"
        lines.append(f"| {p['name']} | "
                     f"{'; '.join(str(e.get('target'))[:60] for e in was) or '-'} | "
                     f"{'; '.join(typed) or '-'} | "
                     f"{', '.join(pe)} | {', '.join(me) or '(none)'}{cover} |")
    lines.append("")

    # --- price fractions
    lines.append("## Inputs against the book's fraction (plan §5.9)\n")
    lines.append("The book: raw materials cost a third of an alchemical item's price (Craft) "
                 "and half of a potion's (Brew Potion). Cheapest bought inputs of the old "
                 "recipe sets, catalysts and apparatus excluded (never spent). An input with "
                 "no price is found or harvested, never sold, and is named.\n")
    lines.append("| Item | Book price | Book fraction | Bought inputs | Over? | Unpriced "
                 "inputs | Source |")
    lines.append("|---|---|---|---|---|---|---|")
    for name, price, src, ids in CLASSICS:
        cost, unpriced = _cost(ids, shelf)
        allow = price * CRAFT_FRACTION
        over = "**over**" if cost > allow + 1e-9 else "within"
        lines.append(f"| {name} | {_gp(price)} | {_gp(round(allow, 2))} | {_gp(cost)} | "
                     f"{over} | {', '.join(unpriced) or '-'} | {src} |")
    for p in pots:
        sl, cl = p["spell_level"], p["caster_level"]
        price = 50 * (sl or 0.5) * cl
        cost, unpriced = _cost(p["materials"], shelf)
        allow = price * POTION_FRACTION
        over = "**over**" if cost > allow + 1e-9 else "within"
        lines.append(f"| {p['name']} | {_gp(price)} | {_gp(allow)} | {_gp(cost)} | {over} | "
                     f"{', '.join(unpriced) or '-'} | CRB potions: 50 × SL {sl} × CL {cl} |")
    lines.append("")

    # --- transmute
    lines.append("## Transmute pairs worth more than 3× their inputs (open point 10)\n")
    lines.append("Every pair the rule allows (plan §9): the same kind, exactly one band "
                 "rarer, sharing at least one essence. Worth is `pricing.worth`, what the "
                 "game prices the material at (an authored price, else the tier ladder "
                 "times the inert factor for a raw material). The input is two units; with "
                 "philosopher's mercury, one. Flagged: output worth more than 3× the two "
                 "units.\n")
    pairs = []
    pool = [d for d in shelf.values() if d["product"] and not d.get("retired")]
    for a in pool:
        for b in pool:
            if a["kind"] != b["kind"] or a["tier"] not in TIERS or b["tier"] not in TIERS:
                continue
            if TIERS.index(b["tier"]) != TIERS.index(a["tier"]) + 1:
                continue
            shared = _benefits(a) & _benefits(b)
            if not shared:
                continue
            wa, wb = _worth(a), _worth(b)
            ratio = wb / (2 * wa) if wa else float("inf")
            pairs.append((ratio, a, b, wa, wb, shared))
    flagged = sorted((p for p in pairs if p[0] > TRANSMUTE_FLAG), key=lambda p: -p[0])
    lines.append(f"{len(pairs)} pairs are possible; **{len(flagged)}** are flagged.\n")
    lines.append("| From (×2) | To | Kind | Shared essence | Worth in | Worth out | ×2 ratio | "
                 "×1 ratio (mercury) |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for ratio, a, b, wa, wb, shared in flagged:
        one = wb / wa if wa else float("inf")
        lines.append(f"| {a['name']} ({a['tier']}) | {b['name']} ({b['tier']}) | {a['kind']} | "
                     f"{', '.join(sorted(shared))} | {_gp(2 * wa)} | {_gp(wb)} | "
                     f"{ratio:.1f} | {one:.1f} |")
    lines.append("")

    lines.append(OPEN_ROWS)
    return "\n".join(lines).rstrip() + "\n"


OPEN_ROWS = """## Open rows for you

1. **The dice ceiling** (proposed in plan §5.6: common 1d4, uncommon 1d6, rare 2d6, exotic
   3d6, legendary 4d6). It trimmed brimstone (1d6 to 1d4), ankheg acid sac (2d4 to 1d6),
   shocker lizard node (1d8 to 1d6), dragon bile (3d6 to 2d6), phlogiston (4d6 to 3d6),
   starfall core (5d6 to 4d6), angel tears (heal 3d8 to 3d6) and phoenix ash (heal 4d8 to
   4d6). Keep the ceiling, or raise a tier?
2. **Resistance counted point for point.** The forge's ceiling counts a resistance of 5 as
   5 points, so salamander ash and winter wolf humour (rare) went from resist 5 to 3, and
   the fire elemental ember (exotic) from 10 to 3. The book's resistances come in steps of
   5; counting a step of 5 as one point would let them stay. Which?
3. **Tarrasque humour's fast healing** went from 5 to 4 (legendary ceiling ±4).
4. **The catalysts' named jobs.** Philosopher's mercury makes Transmute one for one (the
   plan's). The rest are this pass's proposals, written on each catalyst's working trait:
   orichalcum grains (an experiment that fits several formulae is the one you name),
   unicorn horn (strips one drawback, as Filter), mithral dust (pure: the check rolled
   twice), philosopher's wool (a stabilizer too). Brewer's yeast, mother of vinegar, rennet
   and lodestone widen the band only. Philosopher's wool's old heal 1d4 is gone: none of
   lane E's formulae read an essence from it, and a never-spent catalyst's trait would be
   free in every batch (row 14).
5. **Neutral media.** Distilled water and rectified spirits carry no product trait, so an
   essence never leaks into every potion brewed in them. Distilled water is a stabilizer
   (dilution is how a reaction is calmed); font water carries vigour (heal 1d4) and mind
   (+1 morale against fear), which every kind draught brewed in it then carries too. Keep?
6. **Weapon coatings** (saint's tallow, powdered silver's strikes-as-silver, ectoplasm's
   ghost touch, quicklime's +1 damage) use the route `external`, because the vocabulary has
   no `weapon` route. The plan's oil family lists "skin, weapon"; lane F can read
   `external` as the coating, or the vocabulary gains `weapon`.
7. **Poison frequency.** The book's venoms run 1/round for 6 rounds until cured; here a
   venom is one save. A reader for a poison's frequency would make them the book's.
8. **Mishap areas** (plan §8.2, proposed: rare-and-above fire, acid and thunder mishaps
   catch whoever stands beside the bench). Not written: every mishap lands on the
   alchemist only until you rule.
9. **Toxic numbers**: Fortitude DC by tier (11-14 common and uncommon, 14-17 rare and
   exotic, 18-20 legendary) or 1 point of an ability. House.
10. **Transmute economy**: the flagged pairs above. Most of the largest gaps are an unpriced
    common (found or mined, never sold, so `pricing.worth` gives it only the inert ladder,
    under half a gold piece) meeting a priced uncommon. Rule pair by pair, raise the input
    count, or have Transmute's output sell at the ladder rather than its authored price.
11. **Inputs over the book's fraction** (the table above). No price was changed: every
    price passes the one price rule as it stands. The 1st-level potions run 1 to 31 gp
    over their 25 gp allowance because rectified spirits (25 gp) is their medium; the
    3rd-level ones are over because azoth costs 1,500 gp, and the rule's no-inversion check
    keeps azoth (exotic) at or above alkahest (rare, 500 gp), so azoth alone cannot come
    under the 375 gp allowance. Holy weapon balm's inputs are 475 gp against 10. Which
    prices move is yours.
12. **Lane A's ask, outside this lane's files**: an alchemist lore and teacher home,
    `content/rules/alchemy-lore.json`; until it exists the alchemist reads the herbalist's
    rows (tests/test_alchemy_shelf.py says so).
13. **Second essences added for lane E's formulae.** Lane E hand-chose each authored
    formula's essences so the old recipe still makes it. This pass gave the key materials
    those essences where the material could honestly carry one (bear hairs a little
    vigour, owl feathers perception, licorice a lighter step, font water a morale ward
    against fear, azoth a cure for nausea and a resistance to harm, unicorn horn purity and
    mending, and so on: every trait with a note in the tables above). Four are left to you
    and lane E, because nothing in the old recipe has anything to do with what is asked:
    endure elements and smelling salts ask `storm`, align weapon asks `binding`, keen edge
    asks `change`. Either the formula takes another second essence, or a material gains
    the trait.
14. **Catalysts that carry traits.** Unicorn horn is a catalyst (never spent) and now carries
    two traits, because cure moderate wounds and lesser restoration need its purity and
    might. Whether a never-spent catalyst's traits enter every batch it sits in is lane F's
    rule; the proposal is that they do, which is what makes a rare catalyst worth buying.
15. **Vessels the old recipes lack.** The 3rd-level potions' old recipes bottle in the
    crystal retort, which the plan makes apparatus (never spent, §5.9), so those recipes
    have no drinkable vessel until a vial is added; and no vessel in the catalogue has the
    `stick` trait, so the tool family (sunrod, tindertwig, smokestick) has no vessel yet.
    A rod or twig vessel is a new material row for you to approve.
"""


def main() -> int:
    page = build()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != page:
            print("docs/alchemy-review.md is stale: run python tools/alchemy_review.py")
            return 1
        print("docs/alchemy-review.md is current.")
        return 0
    OUT.write_text(page, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
