"""Writes docs/enchanting-review.md: the enchanting data pass laid out for the owner.

Generated from the data, so the page cannot drift from it:

    python tools/enchant_review.py           # write the page
    python tools/enchant_review.py --check   # exit 1 if the page is stale

The "book fixes" and "re-tier" tables compare the catalogue with the version before the
pass (`BEFORE`, the commit lane D branched from), read through git; without git they are
left out and say so.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "pathfindergm.settings")

import django  # noqa: E402

django.setup()

from rules import effectspec, materials, sky  # noqa: E402

OUT = ROOT / "docs" / "enchanting-review.md"
BEFORE = "511cee9"   # build/enchanting at the start of lane D (2026-10-05)

HEAD = """# Enchanting: the data pass, for review

Generated by `tools/enchant_review.py` from `content/materials/enchanter-materials.json` and
`content/materials/magic-items.json`; do not edit by hand (run the tool after changing the
data; `--check` says whether this page is stale). The numbers are written by
`tools/enchant_data_pass.py`, which validates every row before it writes.

How to read it:

- **Book** numbers (every price, caster level, creator level and every amount in a
  recipe's book effects, and what a granted property does) are the printed PF1e ones, read
  by hand from the AoN page each recipe cites. They are listed so you can see the whole
  item, not offered for tuning.
- **House** numbers are this pass's drafts for your judgment: each essence's top-ups, the
  motes of an essence that grants nothing, which family sits in which phase of the day,
  and each family's affinity materials. Top-ups stay inside the ceilings you accepted
  (common and uncommon ±1, rare and exotic ±2, legendary ±3) and are scaled by binding
  quality; drawbacks are in **bold**.
- **Motes**: 1 mote = 100 gp of the book's making cost (your round 4 ruling). A bought
  essence carries exactly the making cost of what it grants on the cheapest item that can
  carry it, so buying the essences for an item costs the book's price. Worked: a +1
  flaming longsword is 8,000 gp market, 4,000 to make, 40 motes = Arcane Essence I (10,
  grants +1) + Flaming Essence (30, grants flaming). Found and harvested essences may carry
  more motes than their grant (a trophy is richer than a shop phial) and are never sold.
- **Tier** is a price band, the one you set for magic items: under 1,000 gp common, under
  5,000 uncommon, under 20,000 rare, under 50,000 exotic, then legendary. An essence is
  banded on the market value its motes carry (motes × 200 gp), which the price rule forces:
  a rarer essence may never cost less than a commoner one, and an essence costs motes ×
  100. The first draft kept lane A's property tiers and failed it (ghost touch exotic at
  3,000 gp under arcane essence III rare at 9,000).
"""

OPEN = """## Open rows for the owner

1. **The phase table** (below): every family's phase and its reason. Seven reasons are
   sourced (frost and stone at dawn, fire at noon, storms in the afternoon, the curfew at
   dusk, the dead at midnight, the cockcrow for light and holy); the rest are house
   readings and say so. **Afternoon** holds electricity, sonic and defending: it is the
   phase you added in round 5, and rules/sky.py's note expected no family to want it.
   Thunderstorms do peak there; dusk is the alternative for the two storm families, noon
   for defending.
2. **Essence tiers move with motes.** 21 of the 81 old essences change tier (the essence
   table's "was" column), 16 of them down: speed, dancing, brilliant energy, heavy
   fortification and warding V from legendary to exotic; the bursts, thundering,
   defending, wounding, invulnerability, warding IV and the middle fortification and spell
   resistance to rare; light fortification to uncommon. Five go up: every +1 weapon
   property is rare (the +1 it adds over a +1 weapon is 6,000 gp of market value), so
   merciful and vicious rise from uncommon, and Arcane I, Warding I and Arcane II carry
   the book's full making cost now (1,000, 500 and 4,000 gp). Lane A's property table
   keeps its own tiers (thundering rare, ghost touch exotic, speed legendary...), so an
   essence and the property it grants can sit in different bands; lane E decides which
   gates the binder's level. The essence's band is the one the price rule can hold.
3. **Legendary is thin among the bought**: Arcane Essence V, the vorpal essence and the
   five greater energy wardings. The legendary trophies (phoenix ember, lich dust, storm
   heart, angel feather, etherealness) are found, never sold. Level 3 opens them.
4. **The ten unsourced catalogue rows** (retired, listed below): delete, or keep as house
   items with house numbers?
5. **Narrow bonuses overreach**: the boots of striding and springing, the ring of jumping,
   the belt of tumbling, the amulet of mighty fists and the lesser bracers of archery carry
   the book's number on every check or attack where the book names a narrower one (jumps,
   threatened squares, unarmed, bows), and the belt of dwarvenkind gives its non-dwarf
   bonuses to anyone. Each says so in `not_yet`. Keep the overreach until a reader can ask
   the purpose, or drop those documents? (The luckstone errs the other way: its saves
   only, not its ability and skill checks.)
6. **Energy resistance essences grant their energy**: `grants` carries the choice
   (`{"property": "energy-resistance", "choice": {"energy": "fire"}}`), a field the
   contract's `grants` shape did not list. Resist Fire Essence binds fire resistance; the
   binder does not choose.
7. **New essences**: eleven bought essences grant the ring and wondrous bonuses no old
   essence could (deflection, natural armour, armour bonus, resistance, the six abilities,
   skill competence), so the rings of protection, cloaks of resistance and ability belts
   in the catalogue can be made at all. Names and families are house.
8. **Top-up bonus types** follow the book's habits (skills competence, saves resistance,
   AC wards insight or natural armour, drawbacks untyped), so a top-up never stacks where
   the book's own items would not; a cloak of resistance and a warding top-up on the same
   save do not add.
"""


def _render(spec: dict) -> str:
    try:
        line = effectspec.render(spec)
    except Exception:
        line = spec.get("type", "?")
    return f"**{line}**" if materials.is_negative(spec) else line


def _grant_words(grants: dict | None) -> str:
    if not grants:
        return "nothing (mote supply)"
    if "enhancement" in grants:
        return f"+{grants['enhancement']} enhancement"
    if grants.get("property"):
        bits = [grants["property"]]
        if grants.get("choice"):
            bits.append(", ".join(f"{v}" for v in grants["choice"].values()))
        if grants.get("bonus"):
            bits.append(f"+{grants['bonus']}")
        return " ".join(bits)
    return f"power {grants.get('power')}"


def _old(path: str):
    try:
        raw = subprocess.run(["git", "show", f"{BEFORE}:{path}"], cwd=ROOT,
                             capture_output=True, check=True).stdout
        return json.loads(raw.decode("utf-8"))
    except Exception:
        return None


def build() -> str:
    ench = json.loads((ROOT / "content/materials/enchanter-materials.json")
                      .read_text(encoding="utf-8"))
    items = json.loads((ROOT / "content/materials/magic-items.json")
                       .read_text(encoding="utf-8"))
    fams = ench["families"]
    rows = [r for r in ench["materials"] if r.get("kind") == "essence"]
    old_e = _old("content/materials/enchanter-materials.json")
    old_tier = {r["id"]: r.get("tier") for r in (old_e or {}).get("materials", [])}
    out = [HEAD, OPEN]

    out.append("## The phases of the day\n")
    out.append("The owner's ruling (round 4 point 10, round 5): phases of the day from "
               "`rules/sky.py`, never a planet. Each family favours one; inside it the "
               "Bind windows are 1.5 times wider (your round 4 number). Counts are "
               "essences on the shelf.\n")
    by_phase = {p: [] for p in sky.PHASES}
    for name, fam in fams.items():
        by_phase.setdefault(fam["phase"], []).append(name)
    out.append("| Phase | Families |\n|---|---|")
    for p in sky.PHASES:
        names = sorted(by_phase.get(p, []))
        out.append(f"| {p} | {', '.join(names) or '(none)'} |")
    out.append("")
    out.append("| Family | Phase | Why | Affinity | Working | Essences |\n"
               "|---|---|---|---|---|---|")
    for name in sorted(fams, key=lambda n: (sky.PHASES.index(fams[n]["phase"]), n)):
        fam = fams[name]
        n = sum(1 for r in rows if r.get("family") == name)
        why = fam["why"].replace("|", "/")
        out.append(f"| {name} | {fam['phase']} | {why} | {', '.join(fam['affinity'])} | "
                   f"{', '.join(fam['working']) or '-'} | {n} |")
    out.append("")

    out.append("## The essences\n")
    out.append(f"{len(rows)} essences ({sum(1 for r in rows if r['id'] not in old_tier)} "
               f"new). Price is motes × 100 for a bought essence; a found one has none. "
               f"\"Was\" is the tier before the pass, where it moved.\n")
    out.append("| Essence | Tier | Was | Family | Polarity | Grants | Motes | Price | "
               "House top-ups | How |\n|---|---|---|---|---|---|---|---|---|---|")
    for r in sorted(rows, key=lambda r: (materials.TIERS.index(r["tier"]), r["family"],
                                         r["id"])):
        was = old_tier.get(r["id"])
        was = "new" if was is None else ("" if was == r["tier"] else was)
        price = f"{r['price_gp']:,}" if r.get("price_gp") else "-"
        house = "; ".join(_render(h) for h in r.get("house") or [])
        out.append(f"| {r['name']} | {r['tier']} | {was} | {r['family']} | "
                   f"{r['polarity']} | {_grant_words(r.get('grants'))} | {r['motes']} | "
                   f"{price} | {house} | {r.get('obtain')} |")
    out.append("")

    wond = [r for r in items["materials"] if r.get("kind") == "wondrous"]
    old_i = _old("content/materials/magic-items.json")
    out.append("## The magic items re-tiered by price\n")
    if old_i is None:
        out.append("(git could not read the catalogue before the pass; run from a "
                   "checkout.)\n")
    else:
        before = {r["id"]: r for r in old_i["materials"]}
        moved = [(r, before[r["id"]]) for r in wond
                 if r["id"] in before and before[r["id"]].get("tier") != r.get("tier")]
        out.append(f"{len(moved)} of {len(wond)} wondrous rows moved (the pricing lane "
                   f"counted 35 before this pass; the Headband of Ponderous Recollection "
                   f"is the 36th, because its book price is 5,100 gp, not 500). Checked on "
                   f"load: `materials.magic_item_tier_problems`.\n")
        out.append("| Item | Price | Was | Now |\n|---|---|---|---|")
        for r, o in sorted(moved, key=lambda x: float(x[0]["price_gp"])):
            out.append(f"| {r['name']} | {float(r['price_gp']):,.0f} | {o.get('tier')} | "
                       f"{r['tier']} |")
        out.append("")

        out.append("## Book fixes in the catalogue\n")
        out.append("Each read from the AoN page in the row's `source` (fetched "
                   "2026-10-05). The old caster levels folded the creator's level "
                   "requirement into the item's caster level (the plan's Ring of "
                   "Protection +4 at CL 20 where the book prints CL 5 and a creator level "
                   "of 12); they are two fields now.\n")
        out.append("| Item | What changed |\n|---|---|")
        for r in wond:
            o = before.get(r["id"])
            if not o or r.get("retired"):
                continue
            bits = []
            if o.get("name") != r.get("name"):
                bits.append(f"name {o.get('name')} → {r.get('name')}")
            if o.get("price_gp") != r.get("price_gp"):
                bits.append(f"price {o.get('price_gp'):,} → {r.get('price_gp'):,} gp")
            if o.get("caster_level") != r.get("caster_level"):
                bits.append(f"CL {o.get('caster_level')} → {r.get('caster_level')}")
            if r.get("creator_level"):
                bits.append(f"creator level {r['creator_level']}")
            old_sp = [o["spell"]] if o.get("spell") else []
            new_sp = [s for g in r.get("spells") or [] for s in g]
            if old_sp != new_sp:
                bits.append(f"spells {', '.join(old_sp) or 'none'} → "
                            f"{', '.join(new_sp) or 'none'}")
            if r.get("creator"):
                bits.append("creator: " + "; ".join(r["creator"]))
            if o.get("slot") != r.get("vessel") and r.get("vessel") != "slotless":
                bits.append(f"slot {o.get('slot')} → {r.get('vessel')}")
            if bits:
                out.append(f"| {r['name']} | {'; '.join(bits)} |")
        out.append("")

    out.append("## Retired: not in the book\n")
    out.append("Not on the Core Rulebook's rings, wondrous items or rods pages, Ultimate "
               "Equipment's slot pages or the Advanced Player's Guide's (all fetched "
               "2026-10-05), nor found by a web search. Kept loadable for old saves; "
               "never offered as recipes.\n")
    out.append("| Id | Name | Price | Why |\n|---|---|---|---|")
    for r in wond:
        if r.get("retired"):
            out.append(f"| {r['id']} | {r['name']} | {float(r['price_gp']):,.0f} | "
                       f"{r.get('why_retired', '')} |")
    out.append("")

    out.append("## What the recipes still cannot run\n")
    waiting: dict[str, int] = {}
    with_not_yet = 0
    live = [r for r in wond if not r.get("retired")]
    for r in live:
        for spec in r.get("book") or []:
            if not effectspec.executable(spec):
                waiting[spec.get("type")] = waiting.get(spec.get("type"), 0) + 1
        if r.get("not_yet"):
            with_not_yet += 1
    out.append(f"{len(live)} recipes, none narrative. Book documents of a type the engine "
               f"does not run yet, by type: "
               + ", ".join(f"{t} {n}" for t, n in sorted(waiting.items()))
               + f". {with_not_yet} recipes say in `not_yet` what of the book they leave "
                 f"out.\n")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    text = build()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("docs/enchanting-review.md is stale: run python tools/enchant_review.py")
            return 1
        print("docs/enchanting-review.md is current.")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
