"""Write the place vocabulary out for World Bible, from the tables themselves.

The twin of `export_race_cues.py`, and it exists for the same reason. A World Bible
session has to know which terrain words parse, which vertical kinds mean anything, and
which words in a settlement's own prose already mint a place — and all of that lives in
`rules/places.py` and `rules/floorplan.py` as Python. A hand-copied list goes stale in the
copy nobody looks at, which is the failure CLAUDE.md names outright, so nobody copies it:
this generates `docs/place-vocabulary.json` and `tools/check_places.py` reads it.

    python tools/export_place_vocab.py

Run it after any change to `places.IMPLIED`, `places.VENTURES`, `places.MOST_SPOTS`,
`places.MOST_IMPLIED`, `biomes.BIOMES`, `floorplan.BY_SPOT`, `floorplan.BY_TERRAIN`,
`floorplan.LOW` or `floorplan.HALL`, and commit what it writes.

**Tier 2 is read now** (2026-09-16, `floorplan.from_world`). `clutter` and `footing` were
marked `"status": "proposed"` here for two releases with the note "no code turns 'dense'
into a count of pillars, because no code reads an authored place at all" — which was true
when it was written and stopped being true the day the reader landed. They carry what each
word actually becomes instead. Everything here is read off the tables and asserted below.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "pathfindergm.settings")
try:
    import django

    django.setup()
except Exception:                                    # the tables need no settings
    pass

from rules import biomes, floorplan, places          # noqa: E402

OUT = ROOT / "docs" / "place-vocabulary.json"

# What each vertical kind means, in an author's words rather than a generator's. Keyed by
# the value `Shape.vertical` actually takes, and asserted complete against the tables
# below — the same arrangement `export_race_cues.py` uses for `_SAYS`, and for the same
# reason: a kind added without a description would ship a list with a hole in it.
_VERTICAL_SAYS: dict[str, str] = {
    "ledge": "a raised band along one side with a rail at its lip to shoot over — "
             "a gallery, a landing over a hall, a wall-walk, a quay",
    "slope": "ground that climbs across the place — hills, a mountain path, "
             "an approach, dunes",
    "scatter": "isolated raised things and no rail — crates, rubble, a cart, roots",
    "none": "flat, and meant to be — a sump, an alley between two walls, "
            "farmland, open steppe",
}

# Tier 2's other two words, and what each one becomes underfoot. Read, not proposed.
_CLUTTER = {
    "bare": "almost nothing in the way",
    "some": "a few things to put between you and an arrow",
    "cluttered": "you cannot cross it in a straight line",
    "dense": "stalls, stacks or trunks, and sight lines of a few squares",
}
_FOOTING = {
    "firm": "boards, flagstones, packed earth",
    "broken": "rubble, roots, spoil — slower in patches",
    "bad": "standing water, deep sand, a floor that is mostly not floor",
}


def _scheme_place_kinds() -> dict:
    """What a quest asks a settlement for. Imported lazily: this exporter runs without
    Django configured in some environments and `schemes` reaches the content loader."""
    try:
        from rules import schemes
        return dict(schemes.PLACE_KINDS)
    except Exception:
        return {}


def _shapes() -> list:
    return list(floorplan.BY_SPOT.values()) + list(floorplan.BY_TERRAIN.values())


def build() -> dict:
    shapes = _shapes()
    kinds = {s.vertical for s in shapes} | {floorplan.Shape().vertical}
    missing = kinds - set(_VERTICAL_SAYS)
    if missing:
        raise SystemExit(f"vertical kind(s) with no description: {sorted(missing)} — "
                         f"add them to _VERTICAL_SAYS in {Path(__file__).name}")

    widths = [s.width * 5 for s in shapes]
    depths = [s.height * 5 for s in shapes]
    ceilings = [s.ceiling * 5 for s in shapes if s.ceiling]
    with_height = sum(1 for s in shapes if s.vertical != "none")

    return {
        "_about": "The vocabulary a World Bible place list may use. Generated by "
                  "tools/export_place_vocab.py from rules/places.py and "
                  "rules/floorplan.py — do not edit by hand. The contract it belongs to "
                  "is docs/places-and-races-for-world-bible.md.",
        "id_grammar": {
            "pattern": "{parent_entity_id}~{terrain}:{slug}[^{storey}]",
            "example": "5bbd0c40345f~urban:the-market",
            "with_storey": "5bbd0c40345f~urban:the-market^1",
            "separators": {"ground": places.SEP, "spot": ":", "storey": places.STOREY},
            "why": "terrain_of() parses this and never looks anything up, so an id "
                   "without its ~terrain segment describes a place standing on nothing "
                   "and the consumer builds open ground.",
        },
        "terrains": sorted(biomes.BIOMES),
        "vertical": _VERTICAL_SAYS,
        "vertical_default": floorplan.Shape().vertical,
        # The places the consumer itself keeps flat, so a checker can name them when an
        # export has reached for verticality everywhere. Generated, not listed: a
        # hand-typed set here would be one more copy of a table to go stale.
        "flat_by_design": sorted(slug for slug, s in floorplan.BY_SPOT.items()
                                 if s.vertical == "none"),
        "vertical_balance": {
            "consumer_tables": f"{with_height} of {len(shapes)}",
            "ratio": round(with_height / len(shapes), 3),
            "why": "the standing instruction is that a generated place is more likely to "
                   "have verticality than not, without being silly about it. This is what "
                   "the consumer's own tables came out at.",
        },
        # What each word is worth on the floor: a fraction of the squares, so the same
        # word means the same density in a closet and in a market square.
        "clutter": {"status": "read", "words": _CLUTTER,
                    "becomes": {k: f"{round(v * 100)}% of the floor blocked"
                                for k, v in floorplan.CLUTTER.items()}},
        "footing": {"status": "read", "words": _FOOTING,
                    "becomes": {k: f"{round(v * 100)}% of the floor difficult"
                                for k, v in floorplan.FOOTING.items()}},
        "ceilings_ft": {
            "house": floorplan.LOW * 5,
            "hall": floorplan.HALL * 5,
            "seen_min": min(ceilings),
            "seen_max": max(ceilings),
            "why": "a house is enough air to stand in and none to fly in. null means "
                   "open sky, and the consumer treats the place as outdoors.",
        },
        "size_ft": {
            "width_min": min(widths), "width_max": max(widths),
            "depth_min": min(depths), "depth_max": max(depths),
            # The clamp as FIELDS, asked for by the supplier 2026-09-16: they apply it
            # before writing so that what they author is what gets laid out, and they
            # were reading it out of the prose below because there was nowhere else to
            # read it from. Parsing a sentence for a number is worse than either side
            # simply publishing it.
            "clamp_min_ft": floorplan.MIN_SQUARES * floorplan.FEET_PER_SQUARE,
            "clamp_max_ft": floorplan.MAX_SQUARES * floorplan.FEET_PER_SQUARE,
            "why": "the range the consumer's own tables cover. An authored value is "
                   "read at five feet to a square and clamped to "
                   f"{floorplan.MIN_SQUARES}-{floorplan.MAX_SQUARES} squares "
                   f"({floorplan.MIN_SQUARES * 5}-{floorplan.MAX_SQUARES * 5} ft): "
                   "below that is a room with nowhere to stand off, above it is more "
                   "map than a player reads.",
        },
        # What a settlement may hold, which is the base draw plus what its own words
        # earned. `most_places` is the one a checker compares against; the parts are here
        # so nobody has to rebuild the sum and get a different answer, which is exactly
        # what happened between this app's generator and its own checker.
        "most_places": places.MOST_IN_A_SETTLEMENT,
        # What a settlement of each size holds, which is the check that actually means
        # something: a village of eighteen rooms is as wrong as a city of five, and one
        # ceiling for both could never say so. The export writes `scale` on every
        # settlement and has since 1.0.
        "places_by_scale": dict(places.PLACES_BY_SCALE),
        "scales": list(places.SCALES),
        "population_by_scale": {k: list(v) for k, v in places.POPULATION_BY_SCALE.items()},
        "always_by_scale": {k: list(v) for k, v in places.ALWAYS_BY_SCALE.items()},
        # The great square and its crossings, which a city has ON TOP of its rooms and
        # which are not counted against its size. Published 2026-09-16 because a checker
        # on either side cannot work out what a legal total is without it — and because
        # this app's own checker was counting them and noting every quartered city.
        "junctions_by_scale": dict(places.JUNCTIONS_BY_SCALE),
        # The four a settlement must have SOMETHING of, whatever else it has and
        # whatever its size: somewhere to buy, somewhere to sleep, somewhere to be quiet
        # and somewhere nobody is watching. This app's own generator has guaranteed them
        # since the table was rebuilt — "a town with no bed in it is a town the player
        # cannot rest in, and 'the generator did not pick one' is not a reason a player
        # can act on" — and it was never published, so an authored world had no way to
        # know. Measured 2026-09-16 on worlds that passed at 0 notes: 25 of Aurvantis's
        # 64 settlements had nowhere to sleep.
        "essential_categories": list(places.ESSENTIAL_CATEGORIES),
        # The place kinds the shipped QUEST CONTENT reaches for, and the room names that
        # satisfy each. Published 2026-09-16 because the category rule above turned out to
        # be too coarse to catch what actually breaks: an arena satisfies "leisure", and a
        # city with an arena and no inn is a city where a scheme that wants somewhere to
        # sleep puts the meeting at the gatehouse. Watched happen, in a test, on a
        # 23-room city.
        #
        # Derived from `rules/schemes.PLACE_KINDS` rather than listed, so a scheme that
        # learns a new slot kind publishes the requirement with it.
        "scheme_place_kinds": {k: list(v) for k, v in _scheme_place_kinds().items() if v},
        # Words from other settlement vocabularies that this app can read, and what it
        # reads them as. Published 2026-09-16 with the ruling that a supplier should send
        # its own six scales rather than flattening them to these three on our behalf:
        # the mapping belongs on the side that decides how many rooms a metropolis has.
        "scale_aliases": dict(places.SCALE_ALIASES),
        "most_generated": places.MOST_SPOTS,
        "most_implied": places.MOST_IMPLIED,
        "most_children_minted_in_play": places.MOST_CHILDREN,
        # Every kind of place a settlement may have, what it is for, the smallest
        # settlement that has one, and whether anything reads it yet.
        "settlement_places": [
            {"name": label, "about": about, "smallest": floor, "category": category,
             "read_by": engine, "staffed": places.staffed(label),
             # Who the app itself stands behind the counter, since 2026-09-16. Published
             # so an author can see that this place already has somebody in it.
             "keeper": places.keeper_of(label)[0]}
            for label, about, floor, category, engine in places.SETTLEMENT_PLACES
        ],
        "implied": [{"place": spot, "slug": _slug(spot), "about": about,
                     "words": list(words)}
                    for words, (spot, about) in places.IMPLIED],
        "ventures": {k: v["label"] for k, v in sorted(places.VENTURES.items())},
        "known_slugs": sorted(floorplan.BY_SPOT),
        "origins": ["world", "found", "venture"],
    }


def _slug(label: str) -> str:
    return label.strip().lower().replace(" ", "-")


def main() -> int:
    OUT.write_text(json.dumps(build(), indent=1, ensure_ascii=False) + "\n",
                   encoding="utf-8")
    v = build()
    print(f"wrote {OUT.relative_to(ROOT)}: {len(v['terrains'])} terrains, "
          f"{len(v['vertical'])} vertical kinds, {len(v['implied'])} cue rows, "
          f"{len(v['ventures'])} ventures, {len(v['known_slugs'])} known slugs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
