"""Write docs/blacksmithing-review.md: every house modifier per material, for the owner.

Balance is a judgment call, so the house numbers go to the owner as a table, the way the
herb hybrid rows did (plan §5.8 step 4). The table is generated from the shipped file
rather than written by hand, so it can never disagree with what the game reads; book
effects are listed separately because they are the book's, not ours to tune.

    python tools/forge_review.py            # write the review
    python tools/forge_review.py --check    # exit 1 if the review is stale
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "pathfindergm.settings")

import django  # noqa: E402

django.setup()

from rules import effectspec, materials  # noqa: E402
from rules.worldclass import TIERS  # noqa: E402

OUT = ROOT / "docs" / "blacksmithing-review.md"

KIND_ORDER = ("metal", "alloy", "fitting", "treatment", "quenchant", "ore", "fuel", "flux")
KIND_TITLE = {"metal": "Metals", "alloy": "Alloys", "fitting": "Fittings (hafts, grips, "
              "guards, linings)", "treatment": "Treatments (finishes)",
              "quenchant": "Quenchants (working traits and the quench mark)",
              "ore": "Ores (assayed for their metal)", "fuel": "Fuels (working traits only)",
              "flux": "Fluxes (working traits only)"}

HEAD = """# Blacksmithing: the house modifiers, for review

Generated by `tools/forge_review.py` from `content/materials/blacksmith-materials.json`;
do not edit by hand (run `python tools/forge_review.py` after changing the data, and
`--check` says whether this page is stale). Every number below that is **not** marked
book is a house modifier drafted in the data pass (lane C, 2026-10-03) for the owner's
judgment, as the herb hybrid rows were.

How to read it:

- **House** numbers start at ±2 (the owner's ruling) and stay inside the tier ceiling:
  common and uncommon ±2, rare and exotic ±3, legendary ±4. Weight moves in steps of
  10%, spell failure in 5%. Every structural list carries at least one drawback, shown
  in **bold**.
- **Book** numbers are printed PF1e rules (docs/blacksmithing-prior-art.md §1.3, §1.4,
  §5.2), applied from the main piece only and never scaled. They are listed so you can
  see the whole material, not offered for tuning.
- Gear numbers are added to the armour table as it stores them: armour check penalty
  is negative there, so "3 lighter" is +3 and a heavier penalty is a negative number.
- A head or body counts in full, a haft, fittings, fastenings or lining at half, so a
  ±2 on a half-weight piece moves the finished item by ±1.

## What the data could not say, and what it asks of other lanes

Book rules with no executable vocabulary yet (kept in each material's `text`, so the
player still reads them, and listed here so they are not forgotten):

- **Fragile** (bronze, copper, tin, gold, viridium): broken on a natural 1. No
  condition-on-item vocabulary.
- **Fire- and frost-forged weapons**: +1d4 energy for 2 rounds after 10+ energy damage.
  No "after exposure" trigger.
- **Living steel**: repairs 2 hp a day; breaks a weapon that rolls a natural 1 against
  its armour. No item repair, no "struck on a natural 1" trigger.
- **Inubrix**: ignores iron and steel armour bonuses, cannot damage iron or steel,
  damage as one size smaller. Approximated by a house +3 attack against a
  metal-armoured target (`when: {"target": {"armour_metal": true}}`, which lane B must
  evaluate).
- **Noqual**: +4 on the *object's* saves against magic. Items have no saves yet. The
  +5,000 gp enchanting surcharge is the field `enchant_surcharge_gp` for the enchanter.
- **Ghost-salt blanch**: full damage to incorporeal creatures until the next hit. Needs
  a `strikes_as` target such as `ghost_touch` (lane A's list); a house stand-in is used.
- **Wyroot**: stores a life point for ki or arcane pools. Approximated by 1 temporary hp
  on a critical, once a day.
- **Abysium**: glows like a candle. No light vocabulary.
- **Singing steel**: speeds bardic performance. Approximated by a house Perform bonus.
- **Horacalcum**: +¼ hit points. Only its hardness is carried.

`when` clauses this data uses that lane B's reader must evaluate (contract §2 names the
first): `{"target": {"type": ...}}` and `{"target": {"subtype": ...}}` against the
struck creature, where a **list** value means "any of"; `{"armour": {"weight": ...}}`
against the base armour at build time (adamantine's DR 1/2/3, horacalcum's initiative,
elysian bronze); `{"attacker": {"type": [...]}}` for elysian bronze's DR against claws
and fists; `{"against": "spell"}` for noqual's saves; `{"weapon":
{"slashing_or_piercing": true}}` for silver's −1 damage.

Quench marks are a single effect (contract §3). Dragon blood's plan wanted resistance on
armour or +1 energy damage on a weapon; it is resistance on both. Styx water's two parts
are one `bundle`.

"""


def _line(spec: dict) -> str:
    text = effectspec.render(spec)
    if spec.get("when"):
        text += f" (when {_when(spec['when'])})"
    if materials.is_negative(spec):
        text = f"**{text}**"
    return text


def _when(when: dict) -> str:
    parts = []
    for key, val in when.items():
        if isinstance(val, dict):
            for k, v in val.items():
                v = " or ".join(v) if isinstance(v, list) else v
                parts.append(f"{key} {k} {v}")
        else:
            parts.append(f"{key} {val}")
    return ", ".join(parts)


def _cell(specs: list[dict]) -> str:
    return "; ".join(_line(s) for s in specs) or "–"


def _pieces(doc: dict) -> str:
    bits = []
    for gear in materials.GEARS:
        if doc["pieces"].get(gear):
            bits.append(f"{gear}: {', '.join(doc['pieces'][gear])}")
    if doc["finishes"]:
        bits.append(f"finishes {', '.join(doc['finishes'])}")
    if doc["feeds"]:
        bits.append(f"feeds {', '.join(doc['feeds'])}")
    if doc["kind"] == "ore" and doc["material"] != doc["id"]:
        bits.append(f"smelts to {doc['material']}")
    return "; ".join(bits) or "–"


def render() -> str:
    docs = [d for d in materials.all().values()
            if d["catalogue"] == materials.FORGE_CATALOGUE]
    out = [HEAD]
    house_count = book_count = 0
    for kind in KIND_ORDER:
        rows = sorted((d for d in docs if d["kind"] == kind),
                      key=lambda d: (TIERS.index(d["tier"]), d["name"]))
        out.append(f"## {KIND_TITLE[kind]}\n")
        if kind in ("metal", "alloy", "fitting", "treatment"):
            out.append("| Material | Tier | Pieces | Weapon (house) | Armour (house) | "
                       "Book | Working |")
            out.append("|---|---|---|---|---|---|---|")
            for d in rows:
                house_w = [e for e in d["weapon"] if not e.get("book")]
                house_a = [e for e in d["armour"] if not e.get("book")]
                book = [f"weapon: {_line(e)}" for e in d["weapon"] if e.get("book")]
                book += [f"armour: {_line(e)}" for e in d["armour"] if e.get("book")]
                house_count += len(house_w) + len(house_a)
                book_count += len(book)
                out.append(f"| {d['name']} | {d['tier']} | {_pieces(d)} | "
                           f"{_cell(house_w)} | {_cell(house_a)} | "
                           f"{'; '.join(book) or '–'} | "
                           f"{', '.join(w['trait'] for w in d['working'])} |")
        elif kind == "quenchant":
            out.append("| Quenchant | Tier | Quench mark (house) | Working |")
            out.append("|---|---|---|---|")
            for d in rows:
                mark = d["quench_mark"] or {}
                if mark.get("type") == "bundle":
                    shown = "; ".join(_line(e) for e in mark.get("effects") or [])
                else:
                    shown = _line(mark) if mark else "–"
                house_count += 1
                out.append(f"| {d['name']} | {d['tier']} | {shown} | "
                           f"{', '.join(w['trait'] for w in d['working'])} |")
        else:
            out.append("| Material | Tier | Use | Working |")
            out.append("|---|---|---|---|")
            for d in rows:
                out.append(f"| {d['name']} | {d['tier']} | {_pieces(d)} | "
                           f"{', '.join(w['trait'] for w in d['working'])} |")
        out.append("")
    out.append(f"Totals: {house_count} house modifiers and quench marks, {book_count} "
               f"book effects, {len(docs)} materials.\n")
    return "\n".join(out)


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("docs/blacksmithing-review.md is stale: run python tools/forge_review.py")
            return 1
        print("review is current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
