"""Write docs/leatherworking-review.md: every house number per leather material, for the owner.

Balance is a judgment call, so the house numbers go to the owner as a table, the forge's
and the alchemist's way (plan §14.7 step 4). The page is generated from the shipped file so
it can never disagree with what the game reads; book effects are listed beside the house
ones and marked, because they are the book's and not ours to tune.

    python tools/leather_review.py            # write the review
    python tools/leather_review.py --check    # exit 1 if the review is stale
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "pathfindergm.settings")

import django  # noqa: E402

django.setup()

from rules import effectspec, materials  # noqa: E402
from rules.worldclass import TIERS  # noqa: E402

OUT = ROOT / "docs" / "leatherworking-review.md"
FILE = ROOT / "content" / "materials" / "leatherworker-materials.json"

HEAD = """# Leatherworking: the data pass, for review

Generated by `tools/leather_review.py` from `content/materials/leatherworker-materials.json`
(and the forge's four leather pieces in `blacksmith-materials.json`); do not edit by hand.
The numbers are written by `tools/leather_data_pass.py`, which validates every row
(`materials.validate`'s leather branch, lane A's `effectspec.leather_effect_problems`, the
price rule) before it writes; `--check` says whether this page is stale. Every number not
marked **book** is a house modifier drafted in this pass (leather lane D, 2026-10-08) for
your judgment.

How to read it:

- **House** numbers start at ±2 (your forge ruling) and stay inside the tier ceiling: common
  and uncommon ±2, rare and exotic ±3, legendary ±4. Weight moves in steps of 10%, spell
  failure in 5%. Every hide's armour list carries at least one drawback, shown in **bold**.
- **Book** numbers are printed PF1e rules (docs/leatherworking-prior-art.md §1.3, confirmed
  against the primary text in its critic pass §7.1), applied from the main piece only and
  never scaled. They are listed so you can see the whole material, not offered for tuning.
- Gear numbers are added to the armour table as it stores them: armour check penalty is
  negative there, so "2 lighter" is +2 and a heavier penalty a negative number.
- A body counts in full; a lacing, a lining, or a grip at half, so a ±2 on a half-weight
  piece moves the finished item by ±1.
- A hide's AC is a `material` bonus: it folds into the suit's armour bonus (the forge's
  rule) instead of meeting it as a second armour bonus that never stacked (inventory §0.2).

## Your rulings this pass follows (2026-10-08)

- **Marks, kept as planned** (held that morning, decided the same day). A tannin, oil,
  wax, thread or dye carries working traits and at most one small mark (plan §14.6): an
  item effect it leaves, once and unscaled, on what it was worked into, by the step that
  used it (Tan, Curry, Tool, Stitch, Dye). One mark per consumable kind on an item, the
  body's first; two marks of one kind give the higher. "The marks" below lists them; each
  is a house number for your review, and a property the player discovers by Grade.
- **Reduced DR.** A hand-written DR on a named hide follows your generic-hide rule: the
  creature's printed DR N/x gives `DR max(1, N/5)/x`, on rare-and-up hides only, as one of
  the hide's house modifiers. Four hides carry one (salamander, noble salamander, phoenix,
  tarrasque). The old DR on dire boar, cave bear and purple worm had no source in the book
  (none of those creatures has DR) and is gone.
- **Generic hides** carry only their own house modifiers here. The creature's energy
  resistance, reduced DR, tier (from CR) and `thick` (natural armour +5) are lane C's, read
  from the stat block at harvest, never stored on these documents.
- **The field kit** (a small kettle now: Harden common and uncommon hides in the field) is a
  goods row (`rules/goods.py`, like the smith's and the alchemist's kits), not a material, so
  it is not on this page; see "What it asks of other lanes".

"""

LISTS = (("armour", "Armour"), ("weapon", "Grip (weapon)"))


def _when(when: dict) -> str:
    parts = []
    for key, val in (when or {}).items():
        if isinstance(val, dict):
            for k, v in val.items():
                v = " or ".join(v) if isinstance(v, list) else v
                parts.append(f"{key} {k} {v}")
        else:
            parts.append(f"{key} {val}")
    return ", ".join(parts)


def _line(spec: dict) -> str:
    text = effectspec.render(spec)
    if spec.get("type") == "damage_reduction":
        text = f"DR {spec.get('amount')}/{spec.get('bypass') or '—'}"
    if spec.get("when"):
        text += f" (when {_when(spec['when'])})"
    if materials.is_negative(spec):
        text = f"**{text}**"
    if spec.get("book"):
        text = f"book: {text}"
    return text


def _cell(specs) -> str:
    return "; ".join(_line(s) for s in specs) or "–"


def _pieces(doc: dict) -> str:
    bits = []
    for gear in materials.GEARS:
        if doc["pieces"].get(gear):
            bits.append(f"{gear}: {', '.join(doc['pieces'][gear])}")
    return "; ".join(bits) or "–"


def _traits(doc: dict) -> str:
    return ", ".join(w["trait"] for w in doc["working"]) or "–"


def _price(doc: dict) -> str:
    p = doc.get("price_gp")
    if p in (None, "", 0):
        return "not sold"
    return f"{p:g} gp" if isinstance(p, (int, float)) else str(p)


def _order(docs):
    return sorted(docs, key=lambda d: (TIERS.index(d["tier"]), d["name"]))


def _tanning_times(tannins) -> list[str]:
    """Each tannage's wait and each tannin's, as the bench charges them (`lw.tan_wait`, the
    plan's own reckoning) and the vat rent a town tannery takes for it (`market.vat_cost`),
    so the page cannot show a wait or a rent the game does not."""
    from rules import leatherworker as lw
    from rules import market, sky

    rows = lw.bench_rules().get("tannages") or {}

    def span(m: int) -> str:
        return sky.span_words(m) if m else "none"

    def rent(kind: str, m: int) -> str:
        if rows[kind].get("where") != "tannery" or rows[kind].get("vat", True) is False:
            return "no vat"
        return _cp(market.vat_cost(m / 1440, 1))

    out = ["## Tanning times (shortened 2026-10-09)\n",
           "Your word after the final pass: \"shorten the tan\". The pass measured a harvested "
           "hide to leather armour at 42 days in the vat (bark's 4 weeks x oak bark's "
           "`slow_tan` 1.5, 8 gp 4 sp of vat rent). Every wait was divided by six, one divisor "
           "for all six tannages, so their order and ratios stand: rawhide 1 day, mineral 3 "
           "days, alum 1 week, bark 4 weeks (8 thick), planar 6 weeks before. The vat rent is "
           f"{_cp(market.vat_cost(1, 1))} a vat a day, a day begun a day paid, so it fell "
           "with the wait. A tannin's and "
           "the hide's `fast_tan` (x0.5) and `slow_tan` (x1.5) still scale the wait; rawhide "
           "is only dried, so nothing moves it.\n",
           "| Tannage | Level | Where | Wait | Thick hide | Vat rent, one vat |",
           "|---|---|---|---|---|---|"]
    for kind, row in sorted(rows.items(), key=lambda kv: (int(kv[1].get("wait_minutes", 0)),
                                                          kv[0])):
        m = lw.tan_wait(kind)
        thick = lw.tan_wait(kind, thick=True)
        out.append(f"| {row.get('name', kind)} | {row.get('level', 1)} | "
                   f"{'tannery vat' if row.get('where') == 'tannery' else 'kit (carried)'} | "
                   f"{span(m)} | {span(thick) if thick != m else '-'} | {rent(kind, m)} |")
    out.append("")
    out.append("Each tannin on a hide with no time trait of its own (a wolf pelt); a deer "
               "hide's `fast_tan` halves these, a boar's `slow_tan` and `thick` lengthen them.\n")
    out.append("| Tannin | Tannage | Time trait | Wait | Vat rent, one vat |")
    out.append("|---|---|---|---|---|")
    for d in tannins:
        kind = d["tannage"]
        if kind not in rows:
            continue
        working = [w["trait"] for w in d["working"]]
        timing = ", ".join(t for t in working if t in ("fast_tan", "slow_tan")) or "-"
        m = lw.tan_wait(kind, working)
        out.append(f"| {d['name']} | {rows[kind].get('name', kind)} | {timing} | {span(m)} | "
                   f"{rent(kind, m)} |")
    out.append("")
    return out


def _cp(cp: int) -> str:
    gp, rest = divmod(int(cp), 100)
    sp, cp = divmod(rest, 10)
    parts = [f"{gp} gp"] * bool(gp) + [f"{sp} sp"] * bool(sp) + [f"{cp} cp"] * bool(cp)
    return " ".join(parts) or "0 cp"


def render() -> str:
    shelf = materials.all()
    docs = [d for d in shelf.values() if d["catalogue"] == materials.LEATHER_CATALOGUE]
    hides = [d for d in docs if d["kind"] == "hide"]
    dragons = [d for d in hides if d["id"].endswith("-dragonhide")]
    generic = [d for d in hides if d["id"].startswith("generic-")]
    named = [d for d in hides if d not in dragons and d not in generic]
    raw = json.loads(FILE.read_text(encoding="utf-8"))
    marked = [d for d in docs if d.get("mark")]
    consumables = [d for d in docs if d["kind"] in materials.LEATHER_CONSUMABLES]
    short = [d for d in consumables
             if materials.properties(d) < materials.CONSUMABLE_PROPERTIES]

    out = [HEAD]
    house = book = 0
    for d in docs:
        for g in materials.EFFECT_GEARS:
            for e in d[g]:
                if e.get("book"):
                    book += 1
                else:
                    house += 1

    # --- the counts ----------------------------------------------------------------------
    by_kind: dict[str, int] = {}
    for d in docs:
        by_kind[d["kind"]] = by_kind.get(d["kind"], 0) + 1
    narrative = sum(1 for d in docs for g in materials.EFFECT_GEARS for e in d[g]
                    if e.get("type") == "narrative")
    legacy_narr = sum(1 for e in (r.get("effects") or [] for r in raw["materials"])
                      for x in e if x.get("type") == "narrative")
    out.append("## The counts\n")
    out.append(f"- **{len(docs)} materials** ({', '.join(f'{k} {v}' for k, v in sorted(by_kind.items()))}).")
    out.append(f"- **{house} house modifiers and {book} book effects** on the item lists; "
               f"{narrative} narrative in them (96 of 171 before the pass), and "
               f"{legacy_narr} narrative left in the legacy `effects` the old chain bench "
               f"reads.")
    grips = [d for d in hides if materials.grip_capable(d)]
    out.append(f"- **{len(grips)} grip-capable hides** carry a weapon list: "
               f"{', '.join(d['name'] for d in _order(grips))}. No other hide does.")
    thick = [d for d in hides if any(w['trait'] == 'thick' for w in d['working'])]
    out.append(f"- **{len(thick)} thick hides** can be the body of hide armour (plan §14.4): "
               f"{', '.join(d['name'] for d in _order(thick))}.")
    out.append(f"- **{len(marked)} consumables carry a mark** (below).")
    out.append(f"- **{len(consumables) - len(short)} of {len(consumables)} consumables** reach "
               f"the plan's {materials.CONSUMABLE_PROPERTIES} discoverable properties with "
               f"their mark counted; {len(short)} do not (listed under \"What the data could "
               f"not say\").")
    out.append("")

    # --- book fixes ------------------------------------------------------------------------
    out.append("## The book fixes (plan §14.5, §15)\n")
    out.append("Each contradiction the questions doc found, corrected to the printed rule. "
               "Before is what the catalogue said; now is what the document carries.\n")
    out.append("| Material | Before | Now (book) | House top-up |")
    out.append("|---|---|---|---|")
    fixes = [
        ("The 11 dragonhides", "wearer resistance 5 to the dragon's energy; masterwork only "
         "with Tool; always `leather` AC 2",
         "the ARMOUR is immune to the dragon's energy (the wearer is not); energy-resistance "
         "enchantments on it cost 25% less; always masterwork; a druid may wear it; hardness "
         "10, 10 hp per inch; thick (makes hide armour); its scales are a form for the "
         "forge's scale suits",
         "wearer resistance 2, one positive by colour, **weighs 20% more**"),
        ("Eel hide (`electric-eel-skin`)", "electricity resistance 2 only",
         "check penalty 1 better, max Dex +1, electricity resistance 2 (the wearer's, by the "
         "book); always masterwork; leather, hide or studded leather only",
         "**hardness -2**"),
        ("Angelskin (new; the forge's binding is a form of it)",
         "Will +3, AC +2, Diplomacy -3 presented as the book's",
         "hardness 5; always masterwork; leather, hide or studded leather only; the aura "
         "clauses are kept as words (`not_yet`): nothing in the app reads alignment",
         "Will +2, Diplomacy +2, **Stealth -2**"),
        ("Darkleaf cloth (new)", "absent",
         "spell failure 10% lower, max Dex +2, check penalty 3 better, half weight, hardness "
         "10, 20 hp per inch; always masterwork; padded, leather, studded leather or hide",
         "**Stealth -2** (every printed effect is a benefit; the validator asks for one "
         "drawback)"),
        ("Griffon mane (new)", "absent",
         "+2 competence on Fly; padded or quilted cloth (and cloaks); cheaper flight "
         "enchantments kept as words (`not_yet`)",
         "AC +2, **weighs 20% more** (plan said +10%: the floor is 2 points, so +20%)"),
        ("Bone studs (new)", "absent",
         "armour bonus -1, check penalty 1 better, hardness 5, no metal (a druid's studded "
         "leather)", "none"),
        ("Bulette (`bulette-plate`)", "+3 armour-typed AC; \"check penalty two worse\" "
         "(prose)",
         "the same statistics as studded leather with no metal (`as_base`)",
         "hardness +2, CMD +2, **check penalty 2 heavier**"),
        ("\"Check penalty one worse\" (boar, crocodile, dire boar, ankheg, cave bear...)",
         "narrative", "–", "typed: `gear_mod acp -2` (house numbers start at 2)"),
        ("\"Never reduces max Dex\" (deer, monitor lizard)", "narrative", "–",
         "typed: `gear_mod max_dex +2`"),
    ]
    for row in fixes:
        out.append("| " + " | ".join(row) + " |")
    out.append("")

    # --- hides ----------------------------------------------------------------------------
    out.append("## The hides\n")
    out.append("Pieces: what the hide can fill (a supple hide is a body, a lacing or a "
               "lining; a rigid plate or shell a body only). Sold as: the form a counter "
               "sells it in, at its price (\"not sold\" means no counter stocks it).\n")
    for tier in TIERS:
        rows = [d for d in _order(named) if d["tier"] == tier]
        if not rows:
            continue
        out.append(f"### {tier.capitalize()}\n")
        out.append("| Hide | Surface | Pieces | Armour | Grip (weapon) | Working | "
                   "Sold as |")
        out.append("|---|---|---|---|---|---|---|")
        for d in rows:
            extra = []
            if d["always_masterwork"]:
                extra.append("always masterwork")
            if d["allowed_bases"]:
                extra.append("only " + ", ".join(d["allowed_bases"]))
            name = d["name"] + (f" ({'; '.join(extra)})" if extra else "")
            out.append(f"| {name} | {d['surface']} | {_pieces(d)} | {_cell(d['armour'])} | "
                       f"{_cell(d['weapon'])} | {_traits(d)} | {d['sold_as']}, "
                       f"{_price(d)} |")
        out.append("")

    out.append("### The dragonhides\n")
    out.append("Every one carries the same four book lines (the armour immune to its "
               "dragon's energy, energy-resistance enchantments 25% cheaper, hardness +8 and "
               "10 hp per inch, always masterwork, druid-permitted) and the same grip. The "
               "house lines are the table.\n")
    out.append("| Dragonhide | Immune (the armour) | House | Grip (weapon) |")
    out.append("|---|---|---|---|")
    for d in _order(dragons):
        imm = next((e["target"] for e in d["armour"] if e["type"] == "object_immunity"), "–")
        hs = [e for e in d["armour"] if not e.get("book")]
        out.append(f"| {d['name']} | {imm} | {_cell(hs)} | {_cell(d['weapon'])} |")
    out.append("")

    out.append("### Generic hides (lane C reads the creature at harvest)\n")
    out.append("| Hide | Surface | Pieces | House armour | Working |")
    out.append("|---|---|---|---|---|")
    for d in _order(generic):
        out.append(f"| {d['name']} (`{d['id']}`) | {d['surface']} | {_pieces(d)} | "
                   f"{_cell(d['armour'])} | {_traits(d)} |")
    out.append("")

    # --- fittings ---------------------------------------------------------------------------
    out.append("## Fittings\n")
    out.append("A fitting fills a fastening. The eight that are forms of a forge metal carry "
               "that metal's armour list exactly (one material, many shelves; the validator "
               "refuses a difference), so steel studs are steel at half weight.\n")
    out.append("| Fitting | Tier | Form of | Armour | Price |")
    out.append("|---|---|---|---|---|")
    for d in _order([d for d in docs if d["kind"] == "fitting"]):
        parent = d["material"] if d["material"] != d["id"] else "–"
        out.append(f"| {d['name']} | {d['tier']} | {parent} | {_cell(d['armour'])} | "
                   f"{_price(d)} |")
    out.append("")

    out.extend(_tanning_times(_order([d for d in docs if d["kind"] == "tannin"])))

    # --- consumables ------------------------------------------------------------------------
    out.append("## Consumables (working traits only)\n")
    out.append("No consumable carries an item list, so no tannin, wax or thread prose "
               "reaches a finished item again (measured before: a boar-hide suit listed "
               "\"The standard tanning agent\" as an effect); what one leaves is its one "
               "mark, below. Each trait is one that is true of the thing. Most dyes, oils "
               "and threads have one or two (\"Props\" counts them, the mark included; the "
               "plan's target is three).\n")
    titles = {"tannin": "Tannins", "oil": "Oils", "wax": "Waxes", "thread": "Threads",
              "dye": "Dyes", "treatment": "Treatments"}
    for kind in ("tannin", "oil", "wax", "thread", "dye", "treatment"):
        rows = _order([d for d in docs if d["kind"] == kind])
        out.append(f"### {titles[kind]}\n")
        if kind == "tannin":
            out.append("| Tannin | Tier | Tannage | Working | Props | Price |")
            out.append("|---|---|---|---|---|---|")
            for d in rows:
                out.append(f"| {d['name']} | {d['tier']} | {d['tannage']} | {_traits(d)} | "
                           f"{materials.properties(d)} | {_price(d)} |")
        else:
            out.append("| Material | Tier | Working | Props | Price |")
            out.append("|---|---|---|---|---|")
            for d in rows:
                salt = " (curing salt)" if materials.is_salt(d) else ""
                out.append(f"| {d['name']}{salt} | {d['tier']} | {_traits(d)} | "
                           f"{materials.properties(d)} | {_price(d)} |")
        out.append("")

    # --- the marks ----------------------------------------------------------------------------
    out.append("## The marks\n")
    out.append("Each is the one small effect the consumable leaves on a finished item (plan "
               "§14.6), from the step that used it, once and never scaled "
               "(`forge_items.build`; `materials.MARK_LIMIT` keeps it small: energy "
               "resistance 1 or 2, a skill +1 or +2, one point of an item number, a save or "
               "a grip's blow +1). Written from the old typed `effects` line the chain bench "
               "laid on every item, the plan's proposal, or the consumable's own text "
               "(wire silk's \"cannot be cut with a knife\", ghost wax's \"weighs less than "
               "it should\"). Not written: mink oil's \"weatherproof\" (soaking is not "
               "modelled; it is mink oil's working trait instead), ghost wax's \"an "
               "incorporeal creature can wear it\" (nothing reads it), dragonblood tannin's "
               "\"resistance 2 to the dragon's energy\" (the tannin names no dragon), and the "
               "plan's light clauses on shadow-black and void dye (the sheet has no dim-light "
               "test; both are standing Stealth marks).\n")
    out.append("| Consumable | Kind | Step | Mark |")
    out.append("|---|---|---|---|")
    for d in sorted(marked, key=lambda d: (materials.MARK_KINDS.index(d["kind"]), d["name"])):
        mark = d["mark"]
        if "type" in mark:
            said = _line(mark)
        else:
            said = "; ".join(f"{_line(e)} (on a {'grip' if g == 'weapon' else g})"
                             for g, e in mark.items())
        out.append(f"| {d['name']} | {d['kind']} | "
                   f"{materials.MARK_STEP[d['kind']].capitalize()} | {said} |")
    out.append("")

    # --- the leatherworker's counter --------------------------------------------------------
    out.append("## What a leatherworker's counter can sell (for lane G)\n")
    out.append("Every settlement's leatherworker sells the craft's supplies (your answer to "
               "open point 9). Each id below has a `price_gp` the price rule accepts "
               "(`pricing.material_price_problems`: 1 gp floor common, 5 gp uncommon). Ids "
               "are unchanged by this pass; brain paste and tawing alum are now kind "
               "`tannin` (plan §8.1 files them as the brain and alum tannins).\n")
    groups = [
        ("Curing salt", lambda d: materials.is_salt(d)),
        ("Tannins", lambda d: d["kind"] == "tannin"),
        ("Oils", lambda d: d["kind"] == "oil"),
        ("Waxes", lambda d: d["kind"] == "wax"),
        ("Threads and sinew", lambda d: d["kind"] == "thread"),
        ("Dyes", lambda d: d["kind"] == "dye"),
        ("Mordant (for a fast dye)", lambda d: d["id"] == "mordant-salts"),
        ("Common hides", lambda d: d["kind"] == "hide" and d["tier"] == "common"
         and not d["id"].startswith("generic-")),
    ]
    for title, keep in groups:
        rows = [d for d in _order(docs) if keep(d) and d.get("price_gp")]
        cells = ", ".join(f"`{d['id']}` {_price(d)}" for d in rows)
        out.append(f"- **{title}**: {cells}.")
    out.append("")
    out.append("**What form a bought hide is in.** A counter sells a hide tanned, never green "
               "(the green hide \"cannot be bought or sold in most settlements\", Harvest "
               "Parts; plan §9). Each hide's `sold_as` says which: `leather` for a smooth or "
               "scaled hide, `fur` (tanned hair-on) for a furred or feathered one; "
               "`price_gp` is the price of that form. Proposed for lane E's stock record: a "
               "bought hide is `form: sold_as`, `tannage: \"oak-bark\"` (a town tannery's "
               "bark tan, so it can be hardened), `grade: 2`, `units` by the hide's size "
               "(plan §5.5), `harvested_at: null`. A green hide sells at 25% of the price, "
               "salted 40%, pelt 50% (plan §9), which is the counter's to compute.\n")

    # --- asks --------------------------------------------------------------------------------
    out.append("## What the data could not say, and what it asks of other lanes\n")
    asks = [
        "**Angelskin's aura** (a moderate good aura; the wearer's evil aura 10 HD weaker; a "
        "20% chance an effect aimed at evil treats an evil wearer as neutral) and **griffon "
        "mane's cheaper flight** are in `not_yet` and the text: no alignment-targeted effect "
        "and no flight cost family exist. The card should say \"book effect, not yet in "
        "play\" from `not_yet` (lane U5's card, lane E's API).",
        "**Bone studs' book effects sit in a fastening**, and `forge_items.build` reads book "
        "effects from the main piece only, so today they never apply. Lane B (or H, which "
        "studs the leather base) must read the fastenings' book effects for bone studs, or "
        "express bone-studded leather another way.",
        "**Minimums the book prints**: eel hide's and darkleaf's check penalty \"to 0\" is "
        "already `armour_row`'s clamp; darkleaf's spell failure \"minimum 5%\" is not (a "
        "darkleaf leather suit computes 10% - 10 = 0%). Lane B: clamp asf at 5 when the "
        "body is darkleaf, or give the build a floor field.",
        "**Prices the book prints per suit** (eel hide +1,200 / +1,800 gp, angelskin +1,000 "
        "/ +2,000, darkleaf +750 / +1,500, dragonhide double the masterwork price with double "
        "Craft progress) are suit surcharges, plan §13.5: lane E's pricing of the product. "
        "Darkleaf's shelf price (375 gp) is half its light-suit surcharge per hide unit; it "
        "is a book document and exempt from the price rule.",
        "**`as_base` and `object_immunity`** wait on lane B's readers (effectspec's honesty "
        "ledger); **the enchanting discount** on the Enchanting price "
        "(`magic_layer._price`).",
        "**Consumables short of three properties.** With marks on, "
        + f"{len(short)} of {len(consumables)} consumables have fewer than "
        f"{materials.CONSUMABLE_PROPERTIES} true things to discover: "
        + ", ".join(f"{d['name']} {materials.properties(d)}" for d in _order(short))
        + ". A dye is fast or fugitive and nothing else the leather list says; a treatment "
        "carries no mark. Prior art §1.5 makes Unchained's material traits (easily worked, "
        "flawless, malleable, pure) rules for leather, but they describe the raw hide, and "
        "giving a dye \"pure\" (the check rolled twice) to make up a count would teach the "
        "player something false and hand cheap dyes a strong bench rule. So the validator's "
        "floor is one working trait (`materials.CONSUMABLE_PROPERTIES_FLOOR`) and the three "
        "is your call: more marks from the texts (glowcap's glimmer, moonlight silver's "
        "light), new leather traits with a bench reader, or a lower target for consumables.",
        "**The field kit** is a goods row like `smith's field kit`: it needs a leatherworker "
        "row in `rules/goods.py` (skinning knife, fleshing beam, round knife, awl and "
        "needles, mallet, and a small kettle that hardens common and uncommon hides) and the "
        "`places.has_field_kit(actor, craft=\"leatherworker\")` reader (lane G / F).",
        "**The forge's rack reads `pieces` (lane H).** Hides name the pieces they fill now, "
        "and `blacksmith._forge_relevant` and `Metal.fills` read `pieces`, so a carried raw "
        "hide shows on the forge's rack and fits a forged suit's lining and fastenings, and "
        "a grip-capable one a weapon's haft, untanned (measured live 2026-10-08: deer hide "
        "on a breastplate's lining and fastenings, \"FITS\"). Contracts §4.5 gives lane H the "
        "rack: it should take leather stock in a form that fills a piece (grip, lacing, "
        "base, scales), never a raw hide.",
        "**`content/rules/base-pieces.json`** gained a `bone-studs` substance row (bone) and "
        "its `leather-grip` row now names `cowhide`, so the material tag and "
        "`materials.material_of` give one answer.",
        "**Flavour the app cannot do**, dropped from the effects and left to the text where "
        "the old text had it: the glowlizard's light, the toad-hide container that stays "
        "dry, the hydra's self-mending, the owlbear's rain-shedding, the kraken's immunity "
        "to water damage, the horse hide's seamless barding panels, the weasel's trim value.",
        "**Bulette plate mail** (65 lb, max Dex +2, hardness 12; Dungeon Denizens Revisited) "
        "is not modelled; `bulette-plate` is the bulette leather. Names wait on the "
        "licensing decision (plan §22), as do the umbral dragon's and the shadow mastiff's.",
        "**Ferrous** is set on iron, wrought iron, cold iron, star-iron, steel, high-carbon, "
        "pattern, nexavaran, living, fire-forged and frost-forged steel. Not on inubrix "
        "(\"ghost iron\" is a skymetal that cannot harm iron), abysium or wyrmsteel.",
    ]
    for a in asks:
        out.append(f"- {a}")
    # Worn goods read the armour list minus the suit-only numbers (plan §18.2); a hide whose
    # positives are all suit numbers gives a cloak nothing but its drawback. Computed, so the
    # list follows the data.
    suit_only = {"ac", "acp", "max_dex", "asf"}
    bare = []
    for d in _order(hides):
        if not d["pieces"].get("worn"):
            continue
        kept = [e for e in d["armour"] if str(e.get("target")) not in suit_only]
        if kept and not any(not materials.is_negative(e) for e in kept):
            bare.append(d["name"])
    if bare:
        out.append(f"- **Worn goods that keep only a drawback.** A cloak, boots or gloves "
                   f"read the armour list without AC, check penalty, max Dex and spell "
                   f"failure (plan §18.2). These hides' positives are all suit numbers, so "
                   f"worn goods of them carry only the drawback: {', '.join(bare)}. Your "
                   f"call whether that is right (thin leather makes poor cloaks) or each "
                   f"wants a worn-good positive.")
    out.append("")
    out.append(f"Totals: {house} house modifiers, {book} book effects, {len(docs)} "
               f"materials, {len(marked)} marks.\n")
    return "\n".join(out)


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("docs/leatherworking-review.md is stale: run python tools/leather_review.py")
            return 1
        print("review is current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
