from django.urls import path

from play import craft_views, home_views, views

urlpatterns = [
    path("", home_views.home, name="home"),
    path("play/", views.table, name="table"),
    path("api/state", views.state, name="state"),
    path("api/sheet", views.sheet, name="sheet"),
    path("api/slots", views.slots, name="slots"),
    path("api/spells/prepare", views.prepare_spells, name="prepare_spells"),
    path("api/level-up", views.level_up, name="level_up"),
    path("api/feats", views.feat_search, name="feat_search"),
    path("licence", views.licence, name="licence"),
    path("api/characters", views.characters, name="characters"),
    path("api/character/new", views.new_character, name="new_character"),
    path("api/character/switch", views.switch_character, name="switch_character"),
    path("api/say", views.say, name="say"),
    path("api/roll", views.roll, name="roll"),
    path("craft/", craft_views.craft_page, name="craft"),
    path("api/world/<str:world_id>", home_views.world_detail, name="world_detail"),
    path("api/bench/<str:bench_id>", home_views.bench, name="bench"),
    path("api/start", home_views.start_in_world, name="start_in_world"),
    path("api/resume", home_views.resume, name="resume"),
    path("api/create/options", home_views.creation_options, name="creation_options"),
    path("api/character/create", home_views.create_character, name="create_character"),
    path("api/homebrew/rules", home_views.house_rules, name="house_rules"),
    path("api/effects/catalogue", home_views.effect_catalogue, name="effect_catalogue"),
    path("api/kinds", home_views.kind_catalogue, name="kind_catalogue"),
    path("api/effects/preview", home_views.effect_preview, name="effect_preview"),
    path("api/consumables", home_views.save_consumable, name="save_consumable"),
    path("api/bench/<str:bench_id>/open/<str:thing_id>", home_views.open_thing,
         name="open_thing"),
    path("api/bench/<str:bench_id>/save", home_views.save_thing, name="save_thing"),
    path("api/spells", home_views.spell_search, name="spell_search"),
    path("api/spells/<str:spell_id>", home_views.spell_detail, name="spell_detail"),
    path("api/craft/ingredients", craft_views.craft_ingredients, name="craft_ingredients"),
    path("api/craft/preview", craft_views.craft_preview, name="craft_preview"),
    path("api/craft/do", craft_views.craft_do, name="craft_do"),
    path("api/craft/recipes", craft_views.craft_recipes, name="craft_recipes"),
    path("api/forage/table", craft_views.forage_table, name="forage_table"),
    path("api/forage", craft_views.forage_do, name="forage_do"),
    path("api/travel", craft_views.travel_to, name="travel_to"),
]
